read subtyping label from the cell paper:

In [9]:
import pandas as pd

cell_paper_df = pd.read_excel("/data1/r20user3/shared_project/Hist2Cell/data/brca_clinical_from_cell_paper/mmc2.xlsx", engine='openpyxl', skiprows=2)
cell_paper_df = cell_paper_df[['Case.ID', 'Final Pathology']]
cell_paper_df

/home/r20user3/anaconda3/envs/gene/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

          Case.ID Final Pathology
0    TCGA-BH-A18G             IDC
1    TCGA-A1-A0SP             IDC
2    TCGA-A2-A04P             IDC
3    TCGA-A2-A04Q             IDC
4    TCGA-A2-A04T             IDC
..            ...             ...
812  TCGA-EW-A2FW           Other
813  TCGA-A1-A0SB           Other
814  TCGA-AR-A1AO           Other
815  TCGA-BH-A1FU           Other
816  TCGA-E2-A108           Other

[817 rows x 2 columns]

read the case id list from our filtered dataset:

In [10]:
from glob import glob

brca_filtered_case_path_list = glob("/data1/r20user3/shared_project/Hist2Cell/data/brca/*")
brca_filtered_case_id_list = [case_path.split("/")[-1] for case_path in brca_filtered_case_path_list]
brca_filtered_case_id_df = pd.DataFrame(brca_filtered_case_id_list, columns=['Slide.ID'])
brca_filtered_case_id_df['Case.ID'] = brca_filtered_case_id_df['Slide.ID'].apply(lambda x: x.split('-01Z')[0])
brca_filtered_case_id_df

                    Slide.ID       Case.ID
0    TCGA-E2-A1IE-01Z-00-DX1  TCGA-E2-A1IE
1    TCGA-AR-A1AT-01Z-00-DX1  TCGA-AR-A1AT
2    TCGA-A2-A0CP-01Z-00-DX1  TCGA-A2-A0CP
3    TCGA-XX-A89A-01Z-00-DX1  TCGA-XX-A89A
4    TCGA-AC-A7VC-01Z-00-DX1  TCGA-AC-A7VC
..                       ...           ...
821  TCGA-AN-A0XN-01Z-00-DX1  TCGA-AN-A0XN
822  TCGA-AO-A0JD-01Z-00-DX1  TCGA-AO-A0JD
823  TCGA-C8-A132-01Z-00-DX1  TCGA-C8-A132
824  TCGA-GM-A3XL-01Z-00-DX1  TCGA-GM-A3XL
825  TCGA-A2-A0CK-01Z-00-DX1  TCGA-A2-A0CK

[826 rows x 2 columns]

pair the filtered case id with the subtyping label, and only keep `IDC` and `ILC` subtypes:

In [14]:
merged_df = pd.merge(brca_filtered_case_id_df, cell_paper_df, on='Case.ID', how='left')
subtyping_df = merged_df[(merged_df['Final Pathology'] == 'IDC') | (merged_df['Final Pathology'] == 'ILC')]
subtyping_df

                    Slide.ID       Case.ID Final Pathology
0    TCGA-E2-A1IE-01Z-00-DX1  TCGA-E2-A1IE             IDC
2    TCGA-A2-A0CP-01Z-00-DX1  TCGA-A2-A0CP             IDC
5    TCGA-C8-A278-01Z-00-DX1  TCGA-C8-A278             IDC
7    TCGA-EW-A3E8-01Z-00-DX1  TCGA-EW-A3E8             ILC
9    TCGA-A2-A0YL-01Z-00-DX1  TCGA-A2-A0YL             ILC
..                       ...           ...             ...
813  TCGA-AC-A2FO-01Z-00-DX1  TCGA-AC-A2FO             ILC
817  TCGA-E9-A1R0-01Z-00-DX1  TCGA-E9-A1R0             IDC
823  TCGA-C8-A132-01Z-00-DX1  TCGA-C8-A132             IDC
824  TCGA-GM-A3XL-01Z-00-DX1  TCGA-GM-A3XL             IDC
825  TCGA-A2-A0CK-01Z-00-DX1  TCGA-A2-A0CK             ILC

[465 rows x 3 columns]

In [15]:
subtyping_df.value_counts('Final Pathology')

Final Pathology
IDC    359
ILC    106
Name: count, dtype: int64

In total, there are 465 cases left, save the paired slide id and subtype label to a csv file:

In [ ]:
subtyping_df.to_csv("/data1/r20user3/shared_project/Hist2Cell/data/brca_clinical_from_cell_paper/filtered_subtyping_label.csv", index=False)