Need to do some filter, so that there is one-to-one relationship between rna and wsi.

In [4]:
import pandas as pd


df = pd.read_csv('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/clinical.tsv', sep='\t', header=0)
df = df[['case_id', 'case_submitter_id']]
df = df.drop_duplicates()
df

                                   case_id case_submitter_id
0     001cef41-ff86-4d3f-a140-a647ac4b10a1      TCGA-E2-A1IU
2     0045349c-69d9-4306-a403-c9c1fa836644      TCGA-A1-A0SB
4     00807dae-9f4a-4fd1-aac2-82eb11bf2afb      TCGA-A2-A04W
6     00a2d166-78c9-4687-a195-3d6315c27574      TCGA-AN-A0AM
8     00b11ca8-8540-4a3d-b602-ec754b00230b      TCGA-LL-A440
...                                    ...               ...
2179  fe15c48b-116d-461e-9b40-68514730fd18      TCGA-A2-A0CP
2181  fe2cd610-aa52-4789-ac62-7683281bb22f      TCGA-PL-A8LX
2183  fe7f74b8-20f4-4471-91dc-4cca8c68e5c0      TCGA-A2-A3XZ
2185  fec0da58-1047-44d2-b6d1-c18cceed43dc      TCGA-E9-A295
2187  ff0f875f-113a-4c0f-8c0a-4259cd496e6d      TCGA-C8-A26W

[1095 rows x 2 columns]

In [5]:
df.to_csv("caseid_to_submitterid.csv")

In [6]:
import json

with open('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/rna_seq_caseid2fileid.json') as f:
    rna_json = json.load(f)
rna_json

[{'data_format': 'TSV',
  'cases': [{'case_id': '011b9b2d-ebe5-42bf-9662-d922faccc7a1',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'de01516e-43f0-4f96-8ac6-ab543a314829.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4220759},
 {'data_format': 'TSV',
  'cases': [{'case_id': '332423a7-8866-4ee3-b08f-3c8d7c16af80',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'e0e050cc-5e2a-41fc-8394-b4816a9dc8a2.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4242201},
 {'data_format': 'TSV',
  'cases': [{'case_id': '389e5b18-8f89-41a9-9fa5-efd4172836e2',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3572211c-0611-4d67-9e71-c5a8f704bd1f.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4240106},
 {'data_format': 'TSV',
  'cases': [{'case_id': '327a2395-85c8-42e1-9638-8e037a1723ed',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '195d8bd4-352c-4407-9319-797d915c72b8.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4248363},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f72c1d69-da35-459f-8542-59bfd6c09c23',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f2ab4258-222d-4a08-a805-3628048ebf1c.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249633},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f5d4c2d3-cc69-4b38-8551-0917e3622a68',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3ffa2cdf-4a54-4362-a6cf-b0567ef69551.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4247939},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'c348a9b3-c901-4384-a222-144387bac0c5',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '316d8a79-9084-4355-9de7-e29503bf0864.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4241720},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd0b78f3f-a198-437a-ab8c-204345d3b75d',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f8ff90c6-3554-4e19-ae56-18f30f51f9b5.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'annotations': [{'annotation_id': '86860d1a-6a46-5217-b181-5c513906a15b'}],
  'file_size': 4242493},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'fac173a8-1613-4bd4-87ba-83a2cfe8a37d',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '5cb07e9d-28b8-41bf-bbb5-b8b56cc12cdc.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4238882},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd13fb44b-291b-4ea4-920c-142daa8d1989',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'c28b080d-8eb9-46b7-9e40-c37409820e17.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4237154},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'ccb22ecc-6e18-44b8-ad48-6ab51314b16e',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'c091a9db-8d3f-4dfb-8658-b6b8020c1d5c.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4252835},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd2694b09-7844-4496-865c-5d3d8cd03330',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '48077485-61e6-4d16-a74c-ee216a9455f1.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4238417},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f63722c1-a0bb-4bf9-8a10-1d76a8e1a0ba',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '69ef0b4d-aa36-46a4-9c7f-96711a51e461.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4246097},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f7ab565c-83b5-4988-b9be-8a46f65dca8c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '42b32308-71f1-4f21-935f-7e4e5751e332.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249043},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f801aeed-dc43-49d7-a319-84c8851979d9',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f9a27067-7485-4c9f-986b-878aa6cd132c.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4251670},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'fe15c48b-116d-461e-9b40-68514730fd18',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'd6450e34-ebf4-4749-a27e-8e3139960afb.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4226836},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f6581eee-61b9-43d4-ab0d-ce5ce3ba1c74',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '95e450bd-ff88-4498-9418-e09883c94988.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4252008},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd10a4887-373b-4726-a61d-126f950e4a06',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '034f8d01-f664-494b-bc04-77485000611f.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4244985},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f81ac8a2-4ce6-439e-b027-1c0bfc88ceaa',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f0bc4292-6662-460a-8bf8-a3c9fa2fd7be.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4219592},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f6e1ec78-5ad9-4879-9b7e-262d17b166ad',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'd28a7c02-2f33-46e2-bff9-5ed518ea6fb6.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4256261},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'fb356957-f620-4d99-b675-1355a1d9f932',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '86538c2f-7f41-4a9b-bea5-f6126772f322.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4231755},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'cc510968-fe52-4109-a79f-74f216b48c78',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '6e79eeb3-9eae-45f4-92a5-fba71c154c1a.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4242177},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd1fd8ed2-be13-4272-b31e-df86911db3b1',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'ba2e1bd2-56f5-4dfb-94b5-92c50c58b31e.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4252801},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd2219a3f-4c55-4dee-9b08-c6f330dd1acf',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'c33e4a5e-f54e-48e0-bcbf-4e019e63a352.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4236158},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4958c36f-1dc7-4f14-9dec-36e14107dbe3',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'c2fe2d79-efb1-4e4d-a297-bd6b15703d10.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4248652},
 {'data_format': 'TSV',
  'cases': [{'case_id': '3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'd9666e09-51bb-49a4-b289-0e6b69636858.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4248482},
 {'data_format': 'TSV',
  'cases': [{'case_id': '495f9eda-b9be-4eef-bae1-766a4bfbd68e',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '4e01a01d-eded-4d02-b8aa-1920c6997726.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4246536},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4aa68586-6331-4795-b40c-859386640df6',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '2e4316d2-5fe5-4ee1-9b22-73f4c42b6202.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4255418},
 {'data_format': 'TSV',
  'cases': [{'case_id': '3dbc8d60-3a97-47b2-91d0-c18fb46b4365',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '62298f43-7f8b-430e-9a23-0ee0ffbc1162.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4227619},
 {'data_format': 'TSV',
  'cases': [{'case_id': '49dc3e68-6206-4f16-969f-a758cc7be8ed',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '75f8fbbb-2015-47cb-94f1-eb88cdfaeae6.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249298},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4da999a0-ef41-4a0b-b1d1-446b39cc855a',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3b509602-c9b3-4dba-86a4-13e2a3857bb4.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249865},
 {'data_format': 'TSV',
  'cases': [{'case_id': '5258294f-ef5b-4091-9183-6bcc545d54b2',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3fab2674-2e00-4748-9d33-9e52631cebfd.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4253482},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4a032bad-e726-48f2-8f39-e3acc109cc91',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'b1e03953-263f-4331-b386-487cdc897425.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4246942},
 {'data_format': 'TSV',
  'cases': [{'case_id': '491b6364-1223-474f-816f-e248c8c841e2',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '8b9d534c-0d48-4d88-bbb2-a866d7e73a55.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4245371},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4a831893-f4ca-4357-a756-b5e954e35dd7',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '39e27085-909a-436b-b8e9-624c16303208.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4246436},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4922cddc-575c-4b8a-8245-ce5f6876760c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'cafc9e36-c5f0-45df-ad03-16210ff0d870.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4256688},
 {'data_format': 'TSV',
  'cases': [{'case_id': '4842bac3-abaa-4900-871f-f2c3ba6457f5',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'ef2a6bd9-fe3b-4b67-942c-89f3a34813ad.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4239942},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'c348a9b3-c901-4384-a222-144387bac0c5',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '71c9a6fc-0538-4533-af51-f7c9defe7770.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4238678},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'c7d7a770-23c0-4310-ab48-1f6152dc2849',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f7efa9c4-e7e2-406a-98e5-596f787c810e.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4247040},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'd111c4ab-b39a-4a7c-8d8e-cb342bc10627',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '790ea932-848f-40cf-ab94-673eea700aa2.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4233860},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'cc348a26-ee11-47a4-8b51-de922967e175',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '2f21d781-2df5-4de1-a595-a61507cfe610.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4261055},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f6ed684f-ee7a-496c-80d5-6eacd494d16a',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'ffe82e73-0990-4d3d-a4d1-7d4e169dfdf5.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4230598},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f89588e9-ca73-4465-a7fb-7246edb45e3a',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '69118aea-1784-49a0-9932-082f87fdec62.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249156},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f947d67f-4aa2-4eb9-977e-21a5ae563613',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '2dc9eaca-6dfc-4e7f-a12b-1495986e1ad4.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4238991},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'ff0f875f-113a-4c0f-8c0a-4259cd496e6d',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'c58a5583-7b04-4b67-9372-e161e18d7de1.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4256989},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'fb3607eb-858e-4ecd-8477-95140658c6d2',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '692ea666-b4ac-4e92-b712-96a67edaef56.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4251095},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'f9eb88f7-9293-46bf-ace4-a746e4ff80dc',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '74179e5e-2d3c-417e-8844-6740ea9fb2e5.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249460},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'cd3faa15-743c-476f-ab0d-f205b14126b6',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'f77281dc-f8c5-4da7-b151-873b03e986ad.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4240552},
 {'data_format': 'TSV',
  'cases': [{'case_id': 'cd781589-3820-45a2-906b-8d60cd02f3ef',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3bbc2702-3fa1-455a-9c68-bf082850d9be.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4239589},
 {'data_format': 'TSV',
  'cases': [{'case_id': '1d38d356-d126-4476-94d0-26616b9375b1',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '00a26384-1b1c-4db4-9664-75fb9b3febdb.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4249777},
 {'data_format': 'TSV',
  'cases': [{'case_id': '21ef1730-e5a7-47ce-b419-d000bb59ae15',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '570b216f-f99d-4be8-b179-48c8d30c6c06.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4255120},
 {'data_format': 'TSV',
  'cases': [{'case_id': '23f438bd-1dbb-4d46-972f-1e8e74ddbd37',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '06a03e45-7315-4a8d-9fef-d841a4a8043c.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4229873},
 {'data_format': 'TSV',
  'cases': [{'case_id': '22eaba28-be67-4730-9846-860bc1fca29a',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'fd2f42a3-d79c-466b-98c2-5f4d0a4a64e9.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4253283},
 {'data_format': 'TSV',
  'cases': [{'case_id': '24e39609-9645-43e5-960b-db5446eaea65',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '13fc37db-3160-4e82-bd63-52fc295e0e19.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4233734},
 {'data_format': 'TSV',
  'cases': [{'case_id': '1a679332-30a3-4495-a2e5-39d299e14333',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '78142fe5-7a8a-49dd-87b5-6a1e6427893e.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4253754},
 {'data_format': 'TSV',
  'cases': [{'case_id': '2585edbd-3488-4100-a4ab-a161252a31ee',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '343c349a-57ce-4599-8185-3ed2e15c6fdd.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4242663},
 {'data_format': 'TSV',
  'cases': [{'case_id': '281f70c5-876f-44b3-84fb-f2302f85e74c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '3a814d3d-749f-4066-b33b-3faf503d84bb.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4248489},
 {'data_format': 'TSV',
  'cases': [{'case_id': '28e9048a-e540-42de-a1f4-4ef894fccc4c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '2dd0b954-db3e-402d-9c06-6160e199dedb.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4250095},
 {'data_format': 'TSV',
  'cases': [{'case_id': '295cf595-4a29-46a3-a0c5-e5f08f947031',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '0ef46de9-c9e7-42f0-92bf-c17dc2ede102.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4253191},
 {'data_format': 'TSV',
  'cases': [{'case_id': '2b19a6b4-7a17-4452-b4aa-6fc18adc0c3c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '2c1b1cbb-6e9f-4416-8faa-abb31d6b4e0e.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4245343},
 {'data_format': 'TSV',
  'cases': [{'case_id': '2e538802-2a31-4774-89a8-c6e4381a887d',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '36bbebb5-ba1e-4ac6-83b2-67ccd05e4939.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4251843},
 {'data_format': 'TSV',
  'cases': [{'case_id': '2b22db1d-54a1-4b9e-a86e-a174cf51d95c',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': '217558e4-a5f5-4c72-91b7-b430a17f457a.rna_seq.augmented_star_gene_counts.tsv',
  'data_category': 'Transcriptome Profiling',
  'file_size': 4251169},
 {'data_format': 'TSV',
  'cases': [{'case_id': '2cf68894-168b-458b-af4f-53cad72989a8',
    'project': {'project_id': 'TCGA-BRCA'}}],

In [7]:
caseid2filename = list()
for idx in range(len(rna_json)):
    caseid2filename.append([rna_json[idx]['cases'][0]['case_id'], rna_json[idx]['file_name']])
caseid2filename[:5]

[['011b9b2d-ebe5-42bf-9662-d922faccc7a1',
  'de01516e-43f0-4f96-8ac6-ab543a314829.rna_seq.augmented_star_gene_counts.tsv'],
 ['332423a7-8866-4ee3-b08f-3c8d7c16af80',
  'e0e050cc-5e2a-41fc-8394-b4816a9dc8a2.rna_seq.augmented_star_gene_counts.tsv'],
 ['389e5b18-8f89-41a9-9fa5-efd4172836e2',
  '3572211c-0611-4d67-9e71-c5a8f704bd1f.rna_seq.augmented_star_gene_counts.tsv'],
 ['327a2395-85c8-42e1-9638-8e037a1723ed',
  '195d8bd4-352c-4407-9319-797d915c72b8.rna_seq.augmented_star_gene_counts.tsv'],
 ['f72c1d69-da35-459f-8542-59bfd6c09c23',
  'f2ab4258-222d-4a08-a805-3628048ebf1c.rna_seq.augmented_star_gene_counts.tsv']]

In [8]:
len(caseid2filename)

1231

In [12]:
case_id_set = set()
replicate_case_id_set = set()
count = 0
for item in caseid2filename:
    if item[0] in case_id_set:
        print(item[0])
        print(item[1])
        count = count + 1
        replicate_case_id_set.add(item[0])
    else:
        case_id_set.add(item[0])

c348a9b3-c901-4384-a222-144387bac0c5
71c9a6fc-0538-4533-af51-f7c9defe7770.rna_seq.augmented_star_gene_counts.tsv
50619f8c-10aa-464a-a227-90a7aa6ffd43
a17d056c-59ee-4c93-9357-19d57f108144.rna_seq.augmented_star_gene_counts.tsv
518f231c-f5f9-4a39-a97b-7fd5666d3e50
a90d3b2d-38f9-455c-88cd-73d5b3729491.rna_seq.augmented_star_gene_counts.tsv
17baef7c-d97d-4b98-ab53-503ef856523d
8f4d89ea-3207-4fa7-9898-9b78cb971577.rna_seq.augmented_star_gene_counts.tsv
0f64edec-0f1f-4025-8a53-75f9534f7828
35ded490-54db-46b8-bc62-a5a9314cf0b2.rna_seq.augmented_star_gene_counts.tsv
14267783-5624-4fe5-ba81-9d67f1017474
8f8c9d55-303c-4099-8038-458e3e96ad4e.rna_seq.augmented_star_gene_counts.tsv
1783cac1-253a-40af-a9ac-48dfb20e1ab8
d7eb3fb0-7bfe-4f69-b298-41dde09902e6.rna_seq.augmented_star_gene_counts.tsv
18eb4dfc-556f-4bf3-a411-4780209ed1e0
d920c232-82ae-48f9-98d1-b94bf4a45d8d.rna_seq.augmented_star_gene_counts.tsv
17c1d42c-cb84-4655-a4cd-b54bae17ecaf
dbd18198-74a5-410d-bf38-08a0ca2fb207.rna_seq.augmented_star_gene_counts.tsv
17c1d42c-cb84-4655-a4cd-b54bae17ecaf
b1366128-6ab0-4205-ae2b-a854e8ad45bf.rna_seq.augmented_star_gene_counts.tsv
d3a75976-67d3-40fa-9f6f-cf2a3d7b773c
144d0f39-feff-4dcd-a07d-abcc400e901f.rna_seq.augmented_star_gene_counts.tsv
d3d4d709-ab34-4617-aa8c-51a3d0a3efe6
b44d9209-0e37-4ffe-9c27-a969a421b3ab.rna_seq.augmented_star_gene_counts.tsv
d4e7426c-9739-4585-9114-e564b13c7c02
cbf0063b-68e5-42ee-9292-dfbf918a7b08.rna_seq.augmented_star_gene_counts.tsv
d6f911b5-e895-43f8-8f86-0ac2f1bc6fae
1b87d18e-4b47-47d0-a6de-1bb9eedb04c9.rna_seq.augmented_star_gene_counts.tsv
d8492ebd-3d94-4a4b-8de7-386526691cc2
58bcabc9-6f6b-43c0-bf40-fa9396c6c9d7.rna_seq.augmented_star_gene_counts.tsv
d8ecba6a-9fff-4993-a799-9a8d2aea524e
28b12d43-f858-458b-9305-6581a9498e59.rna_seq.augmented_star_gene_counts.tsv
db4bc6aa-2e7d-4bcb-8519-a455f624d33b
f48956a3-c821-429f-b1ad-a27133d739bd.rna_seq.augmented_star_gene_counts.tsv
dba9beec-5e51-48c0-9229-0ee286a02a1a
fd98106a-a2c6-4f23-86f5-66436c2501e5.rna_seq.augmented_star_gene_counts.tsv
dd3bfb26-b534-4917-9c4d-9fe7b6477762
68bb844b-1bd7-4828-97d0-e284a7998cbf.rna_seq.augmented_star_gene_counts.tsv
ddcbdac6-9e43-4146-a611-d033125eba14
cfe1c805-2211-419c-bf9a-e0c8b5020dce.rna_seq.augmented_star_gene_counts.tsv
e666081b-caaf-4e8b-9446-807be71201a5
7aac48b4-dbb0-49a5-a3e0-04916a9270b8.rna_seq.augmented_star_gene_counts.tsv
ecab16bc-28d5-4c3a-8735-3c785bd047c4
61a614bb-2249-4611-8aac-1a8e53d4467b.rna_seq.augmented_star_gene_counts.tsv
f130f376-5801-40f9-975d-a7e2f7b5670d
9079bad4-9d01-4eb9-999d-35ad734be2e8.rna_seq.augmented_star_gene_counts.tsv
f130f376-5801-40f9-975d-a7e2f7b5670d
151af32a-7367-4e35-a575-f6da31aa256a.rna_seq.augmented_star_gene_counts.tsv
f954de05-1b44-4087-8933-6cc72d81028d
1880f86a-77c8-4eac-a3e7-a62f5edad8fb.rna_seq.augmented_star_gene_counts.tsv
51ccbf1b-7cae-44ba-991a-11eda8b8c404
12d9d0ec-4e76-4eba-81b1-6dec7b6f2268.rna_seq.augmented_star_gene_counts.tsv
557cb0a3-6f1b-4faf-8296-0a15c24158f9
99df3cc9-683b-449b-bcf4-94bbff09c90e.rna_seq.augmented_star_gene_counts.tsv
5cdae21d-eee5-478f-932a-0f51fcf5f031
3daeb643-20a6-4273-b1fc-eed2a3bb5a18.rna_seq.augmented_star_gene_counts.tsv
4a032bad-e726-48f2-8f39-e3acc109cc91
707fad7d-f284-456a-abfa-17289b40579f.rna_seq.augmented_star_gene_counts.tsv
3c8b5af9-c34d-43c2-b8c9-39ea11e44fa6
bcbe88a9-729e-4af8-9bb8-1ac65aa4bd23.rna_seq.augmented_star_gene_counts.tsv
3b7b9c1e-a84c-47ed-983c-9e4b00cbf01a
7050a8f4-f7f5-41ba-9bda-942d369cf317.rna_seq.augmented_star_gene_counts.tsv
433427a1-bacf-4381-91ba-5fec8a0953f9
98f19a00-fd01-46b1-a75d-f66522ebde2d.rna_seq.augmented_star_gene_counts.tsv
491b6364-1223-474f-816f-e248c8c841e2
e97a2bf2-c5bd-4dbf-9940-450a8a99e9df.rna_seq.augmented_star_gene_counts.tsv
417dea5f-f68e-4dab-940e-43ae8c67e5e6
83f93d3f-d038-4773-a671-0f218f53821c.rna_seq.augmented_star_gene_counts.tsv
5258294f-ef5b-4091-9183-6bcc545d54b2
4bd484be-2364-4a9c-841e-b60bee25af79.rna_seq.augmented_star_gene_counts.tsv
33fe5833-d7a0-43d7-a03d-56985ea448a6
03d891b3-8faf-4384-94ce-2015f1ca5df0.rna_seq.augmented_star_gene_counts.tsv
011b9b2d-ebe5-42bf-9662-d922faccc7a1
e6bad6ec-c178-4684-99e8-2504781a022b.rna_seq.augmented_star_gene_counts.tsv
5fe3c51f-65e2-4da6-8924-a6fae17c022d
eba8b055-6de2-48e7-bed8-40de705ad1d1.rna_seq.augmented_star_gene_counts.tsv
4aa68586-6331-4795-b40c-859386640df6
2e1410fb-4799-4a85-97e2-0d05c9255977.rna_seq.augmented_star_gene_counts.tsv
49dc3e68-6206-4f16-969f-a758cc7be8ed
16e1fcb7-863d-40c1-b2d6-365d519148f6.rna_seq.augmented_star_gene_counts.tsv
4510295e-8aa7-4ef1-b2b7-91cc902f8200
9dd14de1-13c3-4586-8aad-1f3b0cb63de7.rna_seq.augmented_star_gene_counts.tsv
408cb583-6dc3-4698-8bd2-e284042bd5ef
d0ee5ff7-a49a-4633-93a6-40c9e29fb0b7.rna_seq.augmented_star_gene_counts.tsv
478eb8aa-50b8-4ce5-98e4-d518ede4b174
d6cc88bd-b0ba-4606-955d-2dc32e6d2d97.rna_seq.augmented_star_gene_counts.tsv
3ca67cd0-81da-4f68-a9fa-f1a8c013c28d
08429604-2dc7-4827-8ba5-80818aa45a51.rna_seq.augmented_star_gene_counts.tsv
4aa68586-6331-4795-b40c-859386640df6
8f08cee9-a91f-4305-bf8d-efeee9cd386c.rna_seq.augmented_star_gene_counts.tsv
59be60a3-e0f6-4d63-b98c-574ef92428c4
0557d817-20e0-496f-840a-7a15d6da1694.rna_seq.augmented_star_gene_counts.tsv
5d1d00c6-fcae-479e-ae1e-de76efd41d98
741fb6d6-364f-47a0-a262-f18235c48fc4.rna_seq.augmented_star_gene_counts.tsv
327a2395-85c8-42e1-9638-8e037a1723ed
e619b307-4391-48ab-9282-7f22b14f5afe.rna_seq.augmented_star_gene_counts.tsv
2021ed1f-dc75-4701-b8b8-1386466e4802
9ee600fe-20c7-4b1f-b08f-15d3d38a5c52.rna_seq.augmented_star_gene_counts.tsv
20e8106b-1290-4735-abe4-7621e08e3dc8
2b5864c9-7577-4e93-8d22-1f45a98267f1.rna_seq.augmented_star_gene_counts.tsv
24334ac1-28a3-4b61-b590-3f51e375b247
0965a7ff-1a9f-4cc6-a822-970390b2de58.rna_seq.augmented_star_gene_counts.tsv
2b22db1d-54a1-4b9e-a86e-a174cf51d95c
b35809ed-747b-46b9-9921-e14d859e5b5d.rna_seq.augmented_star_gene_counts.tsv
2cf68894-168b-458b-af4f-53cad72989a8
b3861080-a052-4432-82f8-193122ab29d4.rna_seq.augmented_star_gene_counts.tsv
21ef1730-e5a7-47ce-b419-d000bb59ae15
46cdbe65-5610-4903-9452-518fd6d5787d.rna_seq.augmented_star_gene_counts.tsv
011b9b2d-ebe5-42bf-9662-d922faccc7a1
a02fb212-a6cc-40b2-9d31-481fc1ce0911.rna_seq.augmented_star_gene_counts.tsv
233b02f3-c4f0-4a67-9db5-e68d5cdaccb6
98b5b7d9-7f5d-48e0-ad50-7b22f379fef6.rna_seq.augmented_star_gene_counts.tsv
2680da86-c977-4611-b75f-df015283c023
769dff27-1f9c-422d-8ba0-703136a9d5ca.rna_seq.augmented_star_gene_counts.tsv
360d1d6d-cf3e-4c78-b36f-ef5e3160aa6b
f201e2e9-dfb0-4a53-bd68-56f4e87604d3.rna_seq.augmented_star_gene_counts.tsv
214a4507-d974-4b3e-8525-7408fccc6a0f
da549530-7ba5-4302-acd2-40a766860216.rna_seq.augmented_star_gene_counts.tsv
cb9f5e50-f49d-4899-8895-9367afcc1015
db5dab56-838e-4784-a7cf-f05296e356f7.rna_seq.augmented_star_gene_counts.tsv
cb9f5e50-f49d-4899-8895-9367afcc1015
0c814cd9-5b2c-4764-9e6a-6ad0403fcd7d.rna_seq.augmented_star_gene_counts.tsv
ee554215-bea2-4268-aaf9-784e68cdb969
8d2f240f-43c3-4e0d-a6cc-79f6b174dace.rna_seq.augmented_star_gene_counts.tsv
f06f09f3-8133-4a92-ac86-fbe64295e0d8
7880b3ba-9f39-4744-be72-b87dbd8eb425.rna_seq.augmented_star_gene_counts.tsv
f130f376-5801-40f9-975d-a7e2f7b5670d
b4aad532-f92b-43d9-820c-f3c98e382225.rna_seq.augmented_star_gene_counts.tsv
f2622cdb-ac92-42b3-a1ca-67e133c3dd4a
078420d8-5079-4a98-81d7-3a4b84e9d0ad.rna_seq.augmented_star_gene_counts.tsv
f2bbfa9d-9a9d-4f46-9fde-378e4c44e2ad
5a277308-f1bc-47b3-a397-aeabe9db8dc6.rna_seq.augmented_star_gene_counts.tsv
f63722c1-a0bb-4bf9-8a10-1d76a8e1a0ba
c763a483-415e-4cb4-9cdf-4e6c31e8a9c9.rna_seq.augmented_star_gene_counts.tsv
fa176764-a76f-44c7-b97a-cd6d21e052be
c63e3277-327a-4259-84f2-13d9a2c2d68a.rna_seq.augmented_star_gene_counts.tsv
f6581eee-61b9-43d4-ab0d-ce5ce3ba1c74
4497500a-5721-4d7a-8ed9-1ba7b42fb6ab.rna_seq.augmented_star_gene_counts.tsv
f6e1ec78-5ad9-4879-9b7e-262d17b166ad
e869b178-9abe-44ca-ae6b-a6caae1834fb.rna_seq.augmented_star_gene_counts.tsv
67c5f371-3fa9-47c5-8b15-c2dd9acc8519
574d0a5f-8cb7-4783-8d5e-b07c1b3460dc.rna_seq.augmented_star_gene_counts.tsv
6cb6f179-defd-4661-af0a-c353b74c0c49
7d787768-efb1-462d-b5aa-5cbf6fc543d4.rna_seq.augmented_star_gene_counts.tsv
c2aeee6c-ba10-4cf9-b560-c739580f7bf3
61f811cf-9dc1-4f48-ad62-c3ebfd1f0847.rna_seq.augmented_star_gene_counts.tsv
665dd3d3-779c-4abd-b5d7-13342340451d
40a4fc74-f345-4940-be5c-249013782e4f.rna_seq.augmented_star_gene_counts.tsv
64089c20-939f-48b4-ae8b-904ad0597145
37d359b3-d8f5-44cf-8f30-57dfdbbab8c1.rna_seq.augmented_star_gene_counts.tsv
8c7e74e0-71ef-49b8-9217-94b8ef740ef9
e843a939-f1a2-4e98-87b5-69abef893a51.rna_seq.augmented_star_gene_counts.tsv
955d4263-61f7-42e8-8a6e-772a0d6c209d
c0285709-159c-46dd-8bd8-50fad06513dd.rna_seq.augmented_star_gene_counts.tsv
ad18820b-a804-49c0-ba8a-86c09fa6bce2
898f9214-8dab-4b92-9233-70c06c60078c.rna_seq.augmented_star_gene_counts.tsv
b6b1dc9a-91f4-4b0a-afd5-62c9a90c0d5e
34478743-530d-4d71-a124-90ad54ded5c1.rna_seq.augmented_star_gene_counts.tsv
bf3b1481-ae31-4406-b084-b6cc1d7163e3
db5f53f3-6438-4f23-9683-ee16244d98b9.rna_seq.augmented_star_gene_counts.tsv
6cb6f179-defd-4661-af0a-c353b74c0c49
e49fbda2-881a-43c1-9c16-0b07fdd281a7.rna_seq.augmented_star_gene_counts.tsv
6cd9baf5-bbe0-4c1e-a87f-c53b3af22890
56c85bd5-c353-457a-94a9-91a3cc0ac4e0.rna_seq.augmented_star_gene_counts.tsv
6dd0dd7b-62ff-4fd1-a99a-b265f1a91dca
cf5fba05-4996-4f62-adcf-a2ee1f4c65d3.rna_seq.augmented_star_gene_counts.tsv
6b960b58-28e1-41c6-bd6e-7e669c6aa4ef
d4f91697-1c39-4398-bf2f-85217a22ddff.rna_seq.augmented_star_gene_counts.tsv
73ccc949-01b7-48d3-a7c4-c4bcd261672a
a6752916-4437-40a7-bc79-d21f52ad1f41.rna_seq.augmented_star_gene_counts.tsv
7486a2b3-b09f-4e9c-9864-8b51b58d9fb3
18294571-5fc3-4e68-8b31-5fc6a207639f.rna_seq.augmented_star_gene_counts.tsv
858652b8-c4c2-41d8-be32-fdc88e1a7bb0
d504a28c-f8e7-4c5e-b01a-23b4cdd1dd8a.rna_seq.augmented_star_gene_counts.tsv
87f03d04-e651-4a6e-aea6-1c946aa46202
4066800d-0b9e-4263-ba24-cab271630e41.rna_seq.augmented_star_gene_counts.tsv
af577366-0258-49e7-b6af-e70056c081a4
ad01e71e-ed1f-4de6-81b5-8ef60f7a38d0.rna_seq.augmented_star_gene_counts.tsv
c694615c-b1c6-499c-8058-995633ebf948
8fe92722-33b4-421a-9229-7d82e8af0ce2.rna_seq.augmented_star_gene_counts.tsv
6a2972e3-cca9-47e5-aac0-b770f2399eeb
37157138-01ef-49a5-bc74-c45feaf411e2.rna_seq.augmented_star_gene_counts.tsv
7dcf550c-90ce-4f63-aecd-0e46897e2a3e
a41a8b37-2a35-487f-8a4d-ffa0f31b7839.rna_seq.augmented_star_gene_counts.tsv
7bcf6d42-eb8f-4aa2-825b-38671d4f9e3a
5d282b59-c7dc-4f08-ad05-b5eae4bd8e94.rna_seq.augmented_star_gene_counts.tsv
8785012f-f73e-4d68-87cf-1d804af32782
c9f641bc-d9fe-4cd6-8e73-bbf6935aee52.rna_seq.augmented_star_gene_counts.tsv
91a2f2af-e4b1-4a0b-ab20-6a36ce63c533
a4cf670f-1627-42cf-9917-fc2c89708353.rna_seq.augmented_star_gene_counts.tsv
93ed6066-b567-4e1c-ab81-23370f9d3452
e682e28e-0611-4e92-899c-637fde17423d.rna_seq.augmented_star_gene_counts.tsv
9de678e5-67ed-4453-a98b-7ac351d5d0f1
6f73500d-4b23-4f14-911b-fbc69bd38f4b.rna_seq.augmented_star_gene_counts.tsv
9f6be944-83de-42ab-8738-f0022f475e61
d83bb114-c175-4fd5-aac0-5dc04b9218b0.rna_seq.augmented_star_gene_counts.tsv
a8b1f6e7-2bcf-460d-b1c6-1792a9801119
dc3a76a7-bac2-43c0-90e2-e251e459c659.rna_seq.augmented_star_gene_counts.tsv
b3bb8fd6-ee54-4813-b042-2bbe70115382
7b4b9d66-e494-48e8-949f-7cdb42e490f9.rna_seq.augmented_star_gene_counts.tsv
bc0bc70f-c6cf-4dbc-9dc3-8b7bc5f381a4
b58811d7-8ee0-4b65-a892-17319cc9ecaf.rna_seq.augmented_star_gene_counts.tsv
659b0170-e914-45ff-aa55-fcb8d3dc7b8a
d8edd309-518d-4358-8245-9e92d7af4441.rna_seq.augmented_star_gene_counts.tsv
606fbc6a-b41b-441d-9401-51e54912bf5e
4eee2055-ed1f-4958-b214-4cff055c87bd.rna_seq.augmented_star_gene_counts.tsv
69a68fbc-e43d-4652-85ee-693211bded47
89f7da93-c1fd-410b-8479-64ad9bed850e.rna_seq.augmented_star_gene_counts.tsv
6b960b58-28e1-41c6-bd6e-7e669c6aa4ef
9440b088-b04e-4417-9543-5001b0a2b217.rna_seq.augmented_star_gene_counts.tsv
8c7e74e0-71ef-49b8-9217-94b8ef740ef9
1d390e7f-bbbb-45b5-9466-d199f19106b2.rna_seq.augmented_star_gene_counts.tsv
8785012f-f73e-4d68-87cf-1d804af32782
1e742dad-8e44-452a-bf2b-9b8ae1ed8bb2.rna_seq.augmented_star_gene_counts.tsv
8986a141-eae7-4157-b695-02cc6fc3b071
75e67bb5-098c-4b48-8f5d-badc72dc4c47.rna_seq.augmented_star_gene_counts.tsv
94b95984-b2fb-4e42-8887-45e7086c3179
b0c13073-8725-4707-983c-506fe46205d7.rna_seq.augmented_star_gene_counts.tsv
8c7e74e0-71ef-49b8-9217-94b8ef740ef9
d27304e0-1b0b-4fc3-8e0d-af2c305d30f8.rna_seq.augmented_star_gene_counts.tsv
a1093598-d3a8-4ffe-83fc-bc7d1faff7e5
8c0d18d4-98f5-4a66-b62e-7cede666c49f.rna_seq.augmented_star_gene_counts.tsv
9da462b0-93c2-4305-89f6-7199a30399a7
48e1886c-614d-4e2c-bf34-936fd82969c1.rna_seq.augmented_star_gene_counts.tsv
9ddc3e7b-8b54-4a83-8335-8053940f56c1
815b70e5-858d-416d-94aa-6749960883ce.rna_seq.augmented_star_gene_counts.tsv
a32cb96a-78bf-456e-a6ab-2d47b2c67ad4
8aed99b7-de49-4e7e-8fb3-17d897c03e00.rna_seq.augmented_star_gene_counts.tsv
b97bf89a-7a85-4eef-ae7e-f787aead1f0a
31c69703-e318-4e31-aae8-c6cfabe61bc3.rna_seq.augmented_star_gene_counts.tsv
be9bf36a-12e1-4386-addf-1686dc8b49de
d7d4b68a-ab93-4b9c-9cf6-88f15299e306.rna_seq.augmented_star_gene_counts.tsv
6cd9baf5-bbe0-4c1e-a87f-c53b3af22890
240a1e61-5188-4249-b6dd-d6e0d7935d8d.rna_seq.augmented_star_gene_counts.tsv
791c5768-f0f5-4ab6-86eb-998e5c4b49e3
da752364-731c-4e77-8d6e-9c91a5b7f68f.rna_seq.augmented_star_gene_counts.tsv
74f31744-0aed-4633-beec-4e203315f0b7
674907a1-381a-4952-924a-52e2adf5ad19.rna_seq.augmented_star_gene_counts.tsv
7875018b-91dc-4ab1-83b0-ee3883e2816e
a3595c7e-948b-4d93-a623-477d7af84e15.rna_seq.augmented_star_gene_counts.tsv
7eb18190-5a41-4637-9783-f81bbde499e4
682169e0-f36b-430c-896f-c93668b4ce78.rna_seq.augmented_star_gene_counts.tsv
9d166970-07c8-4ca3-9cfa-ed0049df9ecc
078f6959-adcf-44a5-91d2-2581ba3c8e62.rna_seq.augmented_star_gene_counts.tsv
994ca1f5-ad10-44ec-aa21-71fc2940653b
171e095d-2236-43c8-9670-23608e6cc8ab.rna_seq.augmented_star_gene_counts.tsv
96b9c7db-1be1-4b60-b47c-26b654c3d64c
52064107-3c37-45b1-aa6b-a14a98352f9d.rna_seq.augmented_star_gene_counts.tsv
9d95a65b-e41d-4f93-92d4-99dce29ff40d
308e15c9-16b0-4f24-b9dc-e9dc91038579.rna_seq.augmented_star_gene_counts.tsv
a6edb6ca-ae9f-4da7-8ebe-92d83d2987fb
dd1d9d28-3929-4361-a6ff-0ac781fb0ac3.rna_seq.augmented_star_gene_counts.tsv
a851ca14-7bbf-455b-a054-ec03979a4247
4abd29b3-0a83-41d3-a741-bcc5b6d2f98a.rna_seq.augmented_star_gene_counts.tsv
b3264748-947a-43aa-b227-b294fbcc8447
767425eb-9fa2-45bc-a3ad-ca8dbafd373f.rna_seq.augmented_star_gene_counts.tsv
ba39bfbc-5cac-4f6c-b55c-4eee3466ee93
50108c12-718c-48fc-8f76-23ce0c13e2e6.rna_seq.augmented_star_gene_counts.tsv
b2ecbc0f-2c30-4200-8d5e-7b95424bcadb
ec2e3ab8-18a2-4d4e-b0dc-36411ce35357.rna_seq.augmented_star_gene_counts.tsv
cab38ea8-4555-413c-b81e-4621aac4ef85
d81b8303-62b4-46ba-9370-8c6a92cfa4fb.rna_seq.augmented_star_gene_counts.tsv
cc074b7f-d3b2-4880-902e-bf10e667b665
cab9ff29-e575-45e2-a411-1bfdc2e2610c.rna_seq.augmented_star_gene_counts.tsv
02bbb632-0f7f-439d-b8f0-c86a06237424
ca9d1ab5-ea78-46f4-9225-8147639d013c.rna_seq.augmented_star_gene_counts.tsv
0bc5744c-5fa3-45bb-87d0-70a02068b392
3129e1d1-9844-4df4-b30e-29b1c438983b.rna_seq.augmented_star_gene_counts.tsv
0a2a3529-f645-4967-9a58-89ee20b8bb62
343a3d35-e60e-4326-bbf8-2bf722c22ccc.rna_seq.augmented_star_gene_counts.tsv
05135396-df5c-49db-b34e-f4add5b65a2b
2db5e0aa-342e-4766-8725-c1d677fd52b2.rna_seq.augmented_star_gene_counts.tsv

In [14]:
len(replicate_case_id_set)

124

In [16]:
caseid2filename_filtered_rep = list()
for item in caseid2filename:
    if item[0] not in replicate_case_id_set:
        caseid2filename_filtered_rep.append(item)
len(caseid2filename_filtered_rep)

971

In [17]:
caseid2filename_filtered_rep[:5]

[['332423a7-8866-4ee3-b08f-3c8d7c16af80',
  'e0e050cc-5e2a-41fc-8394-b4816a9dc8a2.rna_seq.augmented_star_gene_counts.tsv'],
 ['389e5b18-8f89-41a9-9fa5-efd4172836e2',
  '3572211c-0611-4d67-9e71-c5a8f704bd1f.rna_seq.augmented_star_gene_counts.tsv'],
 ['f72c1d69-da35-459f-8542-59bfd6c09c23',
  'f2ab4258-222d-4a08-a805-3628048ebf1c.rna_seq.augmented_star_gene_counts.tsv'],
 ['f5d4c2d3-cc69-4b38-8551-0917e3622a68',
  '3ffa2cdf-4a54-4362-a6cf-b0567ef69551.rna_seq.augmented_star_gene_counts.tsv'],
 ['d0b78f3f-a198-437a-ab8c-204345d3b75d',
  'f8ff90c6-3554-4e19-ae56-18f30f51f9b5.rna_seq.augmented_star_gene_counts.tsv']]

In [18]:
import json

with open('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/wsi_caseid2fileid.json') as f:
    wsi_json = json.load(f)
wsi_json[:2]

[{'data_format': 'SVS',
  'cases': [{'case_id': '36220587-1c1c-4f92-b177-3b2155e7e273',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'TCGA-AR-A1AU-01Z-00-DX1.F06647D1-E5A3-46FE-8537-01A10A08A4EC.svs',
  'data_category': 'Biospecimen',
  'file_size': 1593743615},
 {'data_format': 'SVS',
  'cases': [{'case_id': '327a2395-85c8-42e1-9638-8e037a1723ed',
    'project': {'project_id': 'TCGA-BRCA'}}],
  'access': 'open',
  'file_name': 'TCGA-BH-A0BC-01Z-00-DX1.7A91831D-9625-49FC-B783-C633F80F898C.svs',
  'data_category': 'Biospecimen',
  'file_size': 1017633449}]

In [20]:
caseid2wsi = list()
for idx in range(len(wsi_json)):
    caseid2wsi.append([wsi_json[idx]['cases'][0]['case_id'], wsi_json[idx]['file_name']])
caseid2wsi[:5]

[['36220587-1c1c-4f92-b177-3b2155e7e273',
  'TCGA-AR-A1AU-01Z-00-DX1.F06647D1-E5A3-46FE-8537-01A10A08A4EC.svs'],
 ['327a2395-85c8-42e1-9638-8e037a1723ed',
  'TCGA-BH-A0BC-01Z-00-DX1.7A91831D-9625-49FC-B783-C633F80F898C.svs'],
 ['3927f736-3b5c-48c8-9d9e-83669ec44770',
  'TCGA-A8-A09G-01Z-00-DX1.B834728C-DAC5-4463-961D-7E3B220905C1.svs'],
 ['3afa1e93-1df8-4e4c-aaa4-557463f4bb77',
  'TCGA-A7-A0DA-01Z-00-DX2.90C93176-C3C6-41B3-B34B-B16F1A1779E6.svs'],
 ['3c612e12-6de8-44fa-a095-805c45474821',
  'TCGA-BH-A0W3-01Z-00-DX1.38DCA2B7-1A54-4FFA-BABA-29F80974BB17.svs']]

In [21]:
case_id_set = set()
replicate_case_id_set = set()
count = 0
for item in caseid2wsi:
    if item[0] in case_id_set:
        print(item[0])
        print(item[1])
        count = count + 1
        replicate_case_id_set.add(item[0])
    else:
        case_id_set.add(item[0])

f7ab565c-83b5-4988-b9be-8a46f65dca8c
TCGA-D8-A1JJ-01Z-00-DX1.a986b48f-b295-4d7a-b778-ce829cdf9c38.svs
c7d7a770-23c0-4310-ab48-1f6152dc2849
TCGA-D8-A1Y2-01Z-00-DX1.77451A0F-00FD-44A9-A0D0-CB7A39CE74CC.svs
fe2cd610-aa52-4789-ac62-7683281bb22f
TCGA-PL-A8LX-01A-02-DX2.84DA8B75-1196-4704-B6B2-C5E7BF645E95.svs
d2694b09-7844-4496-865c-5d3d8cd03330
TCGA-D8-A1XB-01Z-00-DX2.B262C269-F22B-4306-8195-079C0874EF8E.svs
cd7fb75e-1c2e-4201-86d3-b3ba21f476bf
TCGA-OK-A5Q2-01Z-00-DX4.83B45D6C-E350-4436-812F-4155D9F7D331.svs
57af5c72-0d60-4a6b-b1b4-ec6dab90f80f
TCGA-A7-A6VV-01Z-00-DX1.07AE0E16-A883-4C86-BC74-4E13081175F2.svs
2cf68894-168b-458b-af4f-53cad72989a8
TCGA-A7-A13F-01Z-00-DX2.8CC23BAD-B3CC-4BBC-832A-A3879D6EF62D.svs
0b23b5fe-6c7e-4297-bc55-f93fcb830ac4
TCGA-D8-A27R-01Z-00-DX2.31F47D8F-DFD7-42AE-BBBA-7DBBA12FA97D.svs
115bc72c-116f-40c1-be9b-e3dd7650efae
TCGA-D8-A1JE-01Z-00-DX2.CCF3DFEF-E851-425A-BCD0-0F7B377A00BC.svs
ced2c048-b047-43ff-b0e7-cd7ad480850c
TCGA-D8-A1Y0-01Z-00-DX1.10F40197-4174-43CC-AAD3-8CB85154FB2D.svs
d5be2ab3-f748-480d-954b-385cf01b4c81
TCGA-D8-A27N-01Z-00-DX2.EB803DEC-438B-43A9-B906-FD7C3B9A0138.svs
d5e9a403-88ce-40fc-bb85-80cf3f8ff6bc
TCGA-D8-A1J9-01Z-00-DX1.F81FA9EF-8129-4E17-A9AD-2B850782CC18.svs
d69e59a8-b10b-46f5-b859-b6c178d90506
TCGA-A7-A0CJ-01Z-00-DX1.E26F2F62-D688-4373-BB7B-790A06734E49.svs
e783e518-c1e5-4eac-8eaf-e2d65ccd9692
TCGA-S3-AA15-01Z-00-DX2.915A4F90-25CB-4535-99C7-D0D0CFC90412.svs
ea8dbc7a-54c6-469c-865e-f49d00b0223d
TCGA-D8-A73W-01Z-00-DX1.2A4B8A37-BE62-42C8-A109-800A7970FF0F.svs
eb93df3d-9e25-4e4c-9a5d-350f296e5acf
TCGA-D8-A1X5-01Z-00-DX2.E4D28EE2-9C87-4613-BD2E-89FBEF960DEE.svs
cd781589-3820-45a2-906b-8d60cd02f3ef
TCGA-D8-A1JT-01Z-00-DX2.8DB9BB5B-17F3-4D80-835D-872BA275FD3B.svs
cd7fb75e-1c2e-4201-86d3-b3ba21f476bf
TCGA-OK-A5Q2-01Z-00-DX3.5F9215C3-E407-46F8-968E-503D7D14605C.svs
cd7fb75e-1c2e-4201-86d3-b3ba21f476bf
TCGA-OK-A5Q2-01Z-00-DX2.C828A160-87DF-4625-A8C5-2057F61D54F4.svs
42f6f503-4cf6-4a8e-b5fe-b44bccf6b38b
TCGA-D8-A141-01Z-00-DX1.10F6EEB2-C920-43FF-B5A7-B5A651CBDBE3.svs
4958c36f-1dc7-4f14-9dec-36e14107dbe3
TCGA-D8-A145-01Z-00-DX1.34D4EC27-7FD7-4BE2-95A4-CA521CB5590E.svs
55262fcb-1b01-4480-b322-36570430c917
TCGA-3C-AALI-01Z-00-DX1.F6E9A5DF-D8FB-45CF-B4BD-C6B76294C291.svs
530ad151-703d-4638-851f-0b5111ff318b
TCGA-D8-A1JD-01Z-00-DX1.6D215B14-DD90-4635-8645-AF06EBD9BA3F.svs
42e47f3a-dff7-41e4-8f84-146d97e8ab72
TCGA-D8-A1X6-01Z-00-DX1.ABF237D4-708C-46A5-AEF8-58712E5DCC04.svs
62d70067-ff77-4f95-8b69-f537abaf74ce
TCGA-D8-A1J8-01Z-00-DX2.5DCB3447-548D-442C-86B1-CEF79B8689DF.svs
632984bd-dc81-42b6-b024-476cfd0bb2ae
TCGA-D8-A1Y3-01Z-00-DX1.8AA5F695-A06C-4DEA-AD71-16254A48B218.svs
427d0648-3f77-4ffc-b52c-89855426d647
TCGA-3C-AALJ-01Z-00-DX1.777C0957-255A-42F0-9EEB-A3606BCF0C96.svs
27c1c094-690b-4973-8900-a797ad88f98c
TCGA-D8-A27T-01Z-00-DX1.1E3A4D57-9CF2-4EBF-B74D-ADD7BD8CBFA5.svs
2c90d5e3-ac8c-4c86-a06f-42ccc064eb49
TCGA-D8-A1XZ-01Z-00-DX1.8E51A61D-B01C-4A52-8F5D-44D2ABCA46FC.svs
2b19a6b4-7a17-4452-b4aa-6fc18adc0c3c
TCGA-D8-A1XL-01Z-00-DX1.FDF07020-8F40-4C00-9023-E5F40E0D8A7C.svs
2bcacfd1-6a45-4b96-9b80-2ad569b1ab45
TCGA-S3-AA12-01Z-00-DX2.4F0A4F18-41C7-4497-A7B8-5DCE610E08AD.svs
38a631a1-6875-4216-a335-ee93c90a86d6
TCGA-D8-A1Y1-01Z-00-DX1.477390C8-2141-4ADD-813E-25220D2A71FC.svs
2585edbd-3488-4100-a4ab-a161252a31ee
TCGA-D8-A140-01Z-00-DX1.5B9382C0-332C-4FBF-82CD-B9453D02B815.svs
2e243f0e-9d7d-4cb0-9678-70607f90430a
TCGA-A7-A13H-01Z-00-DX1.FCB33A3C-6209-474C-83C1-02551F242937.svs
389e5b18-8f89-41a9-9fa5-efd4172836e2
TCGA-PL-A8LV-01A-01-DX1.88F3D934-96C2-4652-9450-90F2E302FF6D.svs
3afa1e93-1df8-4e4c-aaa4-557463f4bb77
TCGA-A7-A0DA-01Z-00-DX1.5F087009-16E9-4A07-BA24-62340E108B17.svs
1be375fe-5ae5-4e75-a729-69f86a661d9a
TCGA-D8-A73X-01Z-00-DX1.5F0DF75C-594C-42DF-BE3F-E00E5E01DCD6.svs
17baef7c-d97d-4b98-ab53-503ef856523d
TCGA-A7-A0D9-01Z-00-DX1.FBC3B90F-C58B-4476-8354-0AF9248324E3.svs
17f275c1-a0d4-487d-8f02-ea279584b4cd
TCGA-D8-A13Y-01Z-00-DX2.0043D2BB-B04D-4A44-AAB1-1CAAD97AC246.svs
cb9f5e50-f49d-4899-8895-9367afcc1015
TCGA-A7-A0DC-01Z-00-DX1.C770781E-83E4-47DD-B658-25BBBBB32066.svs
ee14e049-b891-4dda-a730-8ce99bd93baf
TCGA-D8-A1XC-01Z-00-DX1.E7494388-838B-4D35-9CA1-77017CBE77F2.svs
f130f376-5801-40f9-975d-a7e2f7b5670d
TCGA-A7-A0DB-01Z-00-DX2.6C6A5F9C-294F-4A86-A0F1-B68D4729B535.svs
77e25ae8-82ec-4dea-8e62-1176f27e47ba
TCGA-D8-A3Z5-01Z-00-DX1.4DBF937F-623C-4212-8493-ECE3C8F555E3.svs
67eef990-5ff4-45d1-843d-d22d7848f130
TCGA-A7-A0CG-01Z-00-DX1.D77019C2-96B1-4EF5-A61E-5F2D5B8D9852.svs
6f6afd31-b5dd-48ab-b18f-6390ba18a5f0
TCGA-D8-A1XF-01Z-00-DX2.1460E522-5B87-4690-8B6B-3183C5D282D6.svs
87b85935-a058-44ad-8fb6-8511130eaffe
TCGA-D8-A1XV-01Z-00-DX1.D0D78B02-2A0D-4107-8083-D2FE1D3F1207.svs
9d95a65b-e41d-4f93-92d4-99dce29ff40d
TCGA-A7-A0CE-01Z-00-DX1.E67322FB-ED25-4B85-B3B0-2B8BD277BB4A.svs
77e25ae8-82ec-4dea-8e62-1176f27e47ba
TCGA-D8-A3Z5-01Z-00-DX2.6196B9FF-F09E-4D44-873D-E53BFB2BF4E1.svs
a6e5f869-1182-4f81-b4bb-cf55261c8f3f
TCGA-D8-A3Z6-01Z-00-DX2.19C6AA07-5D58-46CD-91D0-90DD5CC84022.svs
9087585f-e792-4f33-baaa-56ffe0f745be
TCGA-PL-A8LZ-01A-01-DX1.B9F233EE-06DD-4C14-A392-D2937C7C0868.svs
96f02be7-f2df-483c-8968-a5bd2d887206
TCGA-D8-A73U-01Z-00-DX2.91F571C8-303C-463D-952C-263FAA5097DF.svs
ad6d26ab-6568-40db-bfb0-394d40e801cf
TCGA-D8-A27V-01Z-00-DX2.81E4FFDF-7123-4AC3-BE24-A82564A6C34C.svs
ba80db4e-d899-4da4-ae49-5263d98e1530
TCGA-A7-A5ZX-01Z-00-DX1.A4C651F0-DB8E-4534-84A2-AD875F62209F.svs
cdab777e-62de-4d51-92af-b6eb089c111f
TCGA-D8-A1X7-01Z-00-DX1.3529AEED-2827-4D94-9A8B-32F116EE49D5.svs
7eea2b6e-771f-44c0-9350-38f45c8dbe87
TCGA-A7-A6VX-01Z-00-DX2.9EE94B59-6A2C-4507-AA4F-DC6402F2B74F.svs
9087585f-e792-4f33-baaa-56ffe0f745be
TCGA-PL-A8LZ-01A-03-DX3.E5D16DBF-CABD-4C96-A794-5F27BC305055.svs
9de678e5-67ed-4453-a98b-7ac351d5d0f1
TCGA-A7-A0CH-01Z-00-DX2.81DDF423-FCA8-46CA-83A4-2E80B611844D.svs
6cd9baf5-bbe0-4c1e-a87f-c53b3af22890
TCGA-A7-A13G-01Z-00-DX2.72EF429E-75A7-4D1B-AFFC-8767CB213CDA.svs
70f34c5c-3671-44c8-9469-99f9786efec1
TCGA-D8-A1XR-01Z-00-DX1.7F443346-C564-47B6-9736-6944230CAF46.svs
887b9e5b-99db-44ac-9c30-c0dc6877b41c
TCGA-D8-A1XW-01Z-00-DX2.9849E503-BE3E-417C-ABE8-93A39583DDE0.svs
8785012f-f73e-4d68-87cf-1d804af32782
TCGA-A7-A13D-01Z-00-DX1.D206783C-FA6A-4B6A-B3AA-4132A2C9626B.svs
8c7e74e0-71ef-49b8-9217-94b8ef740ef9
TCGA-A7-A13E-01Z-00-DX1.891954FF-316A-4562-AA14-429631944F22.svs
9ba11ea8-97d3-464a-90a4-ec1151be9088
TCGA-PL-A8LY-01A-02-DX2.6F9520F1-3210-4A96-81C2-A14424F650D1.svs
a6e5f869-1182-4f81-b4bb-cf55261c8f3f
TCGA-D8-A3Z6-01Z-00-DX1.4076A770-5901-4325-85C3-AF7B192272F5.svs
bfa3dbc0-361c-400e-8c10-0aca7049fce9
TCGA-D8-A27W-01Z-00-DX2.4E0D2E4E-5662-4305-8FC2-C651CDDA4998.svs
baf2afc8-f16c-488f-947c-efc9083c6bef
TCGA-D8-A1JI-01Z-00-DX1.9BDB647F-EEAB-4235-BE44-A3815A48CCE0.svs
bdd08ec8-8892-4273-8f21-6fde0f23c52d
TCGA-EW-A423-01Z-00-DX2.5EF1CF39-600A-4ED3-A5A2-AF4435A5F8B5.svs
0130d616-885e-4a6c-9d03-2f17dd692a05
TCGA-D8-A1XY-01Z-00-DX2.33D96E5C-5291-4864-B282-8BACA2043586.svs
09765b0a-94f6-47d2-af56-93368084ac3a
TCGA-A7-A0CD-01Z-00-DX1.F045B9C8-049C-41BF-8432-EF89F236D34D.svs
1026e0bf-5640-4fa5-b65f-4f11e8e76b18
TCGA-D8-A1XS-01Z-00-DX2.ED8BBDB4-CEA6-4E47-8214-4666F3CC6E44.svs
02e6f999-24f2-4ad2-9b92-df3ee2b082e5
TCGA-D8-A1JC-01Z-00-DX1.16D32FE8-4D76-4EEC-9739-D394087605BC.svs

In [22]:
caseid2wsi_filtered_rep = list()
for item in caseid2wsi:
    if item[0] not in replicate_case_id_set:
        caseid2wsi_filtered_rep.append(item)
len(caseid2wsi_filtered_rep)

996

In [24]:
caseid2wsi_filtered_rep[:2]

[['36220587-1c1c-4f92-b177-3b2155e7e273',
  'TCGA-AR-A1AU-01Z-00-DX1.F06647D1-E5A3-46FE-8537-01A10A08A4EC.svs'],
 ['327a2395-85c8-42e1-9638-8e037a1723ed',
  'TCGA-BH-A0BC-01Z-00-DX1.7A91831D-9625-49FC-B783-C633F80F898C.svs']]

In [25]:
caseid2filename_filtered_rep[:2]

[['332423a7-8866-4ee3-b08f-3c8d7c16af80',
  'e0e050cc-5e2a-41fc-8394-b4816a9dc8a2.rna_seq.augmented_star_gene_counts.tsv'],
 ['389e5b18-8f89-41a9-9fa5-efd4172836e2',
  '3572211c-0611-4d67-9e71-c5a8f704bd1f.rna_seq.augmented_star_gene_counts.tsv']]

In [26]:
caseid2rna_wsi = list()

for caseA in caseid2filename_filtered_rep:
    for caseB in caseid2wsi_filtered_rep:
        if caseA[0] == caseB[0]:
            caseid2rna_wsi.append([caseA[0], caseA[1], caseB[1]])

In [27]:
len(caseid2rna_wsi)

880

In [28]:
caseid2rna_wsi[:2]

[['332423a7-8866-4ee3-b08f-3c8d7c16af80',
  'e0e050cc-5e2a-41fc-8394-b4816a9dc8a2.rna_seq.augmented_star_gene_counts.tsv',
  'TCGA-A2-A0CU-01Z-00-DX1.5B77D21C-A497-478B-9752-3730322AD9ED.svs'],
 ['f72c1d69-da35-459f-8542-59bfd6c09c23',
  'f2ab4258-222d-4a08-a805-3628048ebf1c.rna_seq.augmented_star_gene_counts.tsv',
  'TCGA-AR-A1AX-01Z-00-DX1.2389D54F-545E-499E-B392-DD731834460A.svs']]

In [30]:
import os
from glob import glob
import shutil
from tqdm import tqdm


for case in tqdm(caseid2rna_wsi):
    wsi_id = case[2].split('.')[0]
    rna_file_name = case[1]
    os.mkdir(os.path.join('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/organized_RNA_seq', wsi_id))
    des = os.path.join('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/organized_RNA_seq', wsi_id, rna_file_name)
    src = glob('/data1/r20user3/shared_project/Hist2Cell/data/BRCA/RNA_seq/*/'+rna_file_name)[0]
    shutil.copy(src, des)

100%|██████████| 880/880 [01:02<00:00, 14.05it/s]

In [32]:
all_wsi_path = glob("/data1/WSI/TCGA-WSI/BRCA/BRCA/*.svs")
for dir in tqdm(glob("/data1/r20user3/shared_project/Hist2Cell/data/BRCA/organized_RNA_seq/*")):
    for wsi_path in all_wsi_path:
        if dir.split('/')[-1] in wsi_path:
            des = os.path.join(dir, wsi_path.split('/')[-1])
            shutil.copy(wsi_path, des)

  0%|          | 0/880 [00:00<?, ?it/s]

100%|██████████| 880/880 [1:01:40<00:00,  4.20s/it]

In [6]:
from glob import glob

normed_folder = glob("/data1/r20user3/shared_project/Hist2Cell/data/brca/*/patches_normed")
len(normed_folder)

100

In [7]:
import shutil
from tqdm import tqdm

for folder in tqdm(normed_folder):
    shutil.rmtree(folder)

100%|██████████| 100/100 [00:02<00:00, 49.89it/s]

In [5]:
import os
from glob import glob

wsi_path_list = glob("/data1/r20user3/shared_project/Hist2Cell/data/brca/*")
wsi_path_list[:2]

['/data1/r20user3/shared_project/Hist2Cell/data/brca/TCGA-E2-A1IE-01Z-00-DX1',
 '/data1/r20user3/shared_project/Hist2Cell/data/brca/TCGA-AR-A1AT-01Z-00-DX1']

In [9]:
from tqdm import tqdm
import shutil


for wsi_path in tqdm(wsi_path_list):
    wsi_id = wsi_path.split('/')[-1]
    rna_file_path = glob(os.path.join("/data1/r20user3/shared_project/Hist2Cell/data/BRCA/organized_RNA_seq", wsi_id, "*.tsv"))[0]
    des = os.path.join(wsi_path, rna_file_path.split('/')[-1])
    shutil.copy(rna_file_path, des)

  0%|          | 0/826 [00:00<?, ?it/s]

100%|██████████| 826/826 [00:33<00:00, 24.82it/s]

In [1]:
import pandas as pd

df = pd.read_csv("/data1/r20user3/shared_project/Hist2Cell/data/BRCA/clinical.tsv", sep='\t', header=0)
df[['case_submitter_id', 'primary_diagnosis']]

     case_submitter_id                 primary_diagnosis
0         TCGA-E2-A1IU  Infiltrating duct carcinoma, NOS
1         TCGA-E2-A1IU  Infiltrating duct carcinoma, NOS
2         TCGA-A1-A0SB          Adenoid cystic carcinoma
3         TCGA-A1-A0SB          Adenoid cystic carcinoma
4         TCGA-A2-A04W           Apocrine adenocarcinoma
...                ...                               ...
2184      TCGA-A2-A3XZ  Infiltrating duct carcinoma, NOS
2185      TCGA-E9-A295            Lobular carcinoma, NOS
2186      TCGA-E9-A295            Lobular carcinoma, NOS
2187      TCGA-C8-A26W  Infiltrating duct carcinoma, NOS
2188      TCGA-C8-A26W  Infiltrating duct carcinoma, NOS

[2189 rows x 2 columns]

In [4]:
df[['case_submitter_id', 'primary_diagnosis']].describe()

       case_submitter_id                 primary_diagnosis
count               2189                              2189
unique              1095                                23
top         TCGA-E2-A1IU  Infiltrating duct carcinoma, NOS
freq                   2                              1554

In [5]:
df['primary_diagnosis'].value_counts()

primary_diagnosis
Infiltrating duct carcinoma, NOS                            1554
Lobular carcinoma, NOS                                       402
Infiltrating duct and lobular carcinoma                       56
Infiltrating duct mixed with other types of carcinoma         38
Mucinous adenocarcinoma                                       32
Metaplastic carcinoma, NOS                                    28
Infiltrating lobular mixed with other types of carcinoma      12
Intraductal papillary adenocarcinoma with invasion            12
Medullary carcinoma, NOS                                      12
Intraductal micropapillary carcinoma                           8
Paget disease and infiltrating duct carcinoma of breast        6
Pleomorphic carcinoma                                          6
Papillary carcinoma, NOS                                       4
Large cell neuroendocrine carcinoma                            2
Phyllodes tumor, malignant                                     2
Tubular adenocarcinoma                                         2
Cribriform carcinoma, NOS                                      2
Adenoid cystic carcinoma                                       2
Carcinoma, NOS                                                 2
Secretory carcinoma of breast                                  2
Apocrine adenocarcinoma                                        2
Basal cell carcinoma, NOS                                      2
'--                                                            1
Name: count, dtype: int64