In [1]:
import scanpy as sc


brca_cell_adata = sc.read_h5ad("/data1/r20user3/shared_project/Hist2Cell/code/data_preprocessing/brca_cellabundance/brca_cellabundance_estimation.h5ad")
brca_cell_adata

AnnData object with n_obs × n_vars = 880 × 13199
    obs: '_indices', '_scvi_batch', '_scvi_labels'
    uns: '_scvi_manager_uuid', '_scvi_uuid', 'mod'
    obsm: 'means_cell_abundance_w_sf', 'q05_cell_abundance_w_sf', 'q95_cell_abundance_w_sf', 'stds_cell_abundance_w_sf'

In [2]:
brca_cell_label_df = brca_cell_adata.obsm['q05_cell_abundance_w_sf']
brca_cell_label_df.head(2)

,q05cell_abundance_w_sf_CD4-positive helper T cell,"q05cell_abundance_w_sf_CD4-positive, alpha-beta T cell","q05cell_abundance_w_sf_CD8-positive, alpha-beta memory T cell",q05cell_abundance_w_sf_IgA plasma cell,q05cell_abundance_w_sf_IgG plasma cell,q05cell_abundance_w_sf_T cell,"q05cell_abundance_w_sf_activated CD4-positive, alpha-beta T cell","q05cell_abundance_w_sf_activated CD8-positive, alpha-beta T cell",q05cell_abundance_w_sf_alternatively activated macrophage,q05cell_abundance_w_sf_basal cell,...,q05cell_abundance_w_sf_naive B cell,q05cell_abundance_w_sf_natural killer cell,q05cell_abundance_w_sf_neutrophil,q05cell_abundance_w_sf_non-classical monocyte,q05cell_abundance_w_sf_pericyte,q05cell_abundance_w_sf_plasmacytoid dendritic cell,q05cell_abundance_w_sf_regulatory T cell,q05cell_abundance_w_sf_unswitched memory B cell,q05cell_abundance_w_sf_vascular associated smooth muscle cell,q05cell_abundance_w_sf_vein endothelial cell
TCGA-A8-A09R-01Z-00-DX1,0.002925,0.002420,0.010768,0.0259,0.045246,0.222976,0.024620,0.336438,0.060828,2.076841,...,0.006568,0.022835,0.065895,0.043894,0.131588,0.041848,0.070641,0.003808,0.631248,0.011149
TCGA-E2-A1IE-01Z-00-DX1,0.000710,0.000151,0.000354,0.0040,0.001229,0.003494,0.000591,0.000251,0.048617,0.182926,...,0.000041,0.000068,0.000024,0.000088,0.058550,0.000005,0.000034,0.000007,0.632732,0.040799

In [3]:
import pandas as pd

cell_names = [cell[23:] for cell in list(pd.read_csv("/data1/r20user3/shared_project/Hist2Cell/data/her2st/A1/cell_ratio.csv").columns)[1:]]

from glob import glob
tif_list = glob('/data1/r20user3/shared_project/Hist2Cell/data/brca/*')
tif_list.sort()
test_slides = list()
for tif in tif_list:
    tif_path = tif.split('/')[-1]
    test_slides.append(tif_path)
test_slides[:2]

['TCGA-3C-AALK-01Z-00-DX1', 'TCGA-4H-AAAK-01Z-00-DX1']

In [4]:
import joblib
from tqdm import tqdm


pred_id_mena_dict = dict()        
for case in tqdm(test_slides):
    # os.mkdir(os.path.join("/data1/r20user3/shared_project/Hist2Cell/code/analysis/sptial_colocalization/cross_source", case))
    try:
        save_path = "/data1/r20user3/shared_project/Hist2Cell/code/analysis/inference/brca/breast_cross_source_epoch100_lr1e-4_2hop_ensemble_Trans1layer_GNNoutput50_onlycell_"+case+"_best_cell_all_abundance_average.pkl"
        pred_and_label = joblib.load(save_path)
        pred_id_mena_dict[case] = pred_and_label['cell_abundance_predictions'].mean(axis=0)
    except:
        continue

100%|██████████| 826/826 [00:01<00:00, 649.48it/s]

In [5]:
len(pred_id_mena_dict)

585

In [9]:
pred_id_mena_dict.keys()

dict_keys(['TCGA-3C-AALK-01Z-00-DX1', 'TCGA-4H-AAAK-01Z-00-DX1', 'TCGA-5L-AAT1-01Z-00-DX1', 'TCGA-5T-A9QA-01Z-00-DX1', 'TCGA-A1-A0SK-01Z-00-DX1', 'TCGA-A2-A04N-01Z-00-DX1', 'TCGA-A2-A04P-01Z-00-DX1', 'TCGA-A2-A04R-01Z-00-DX1', 'TCGA-A2-A04T-01Z-00-DX1', 'TCGA-A2-A04U-01Z-00-DX1', 'TCGA-A2-A04W-01Z-00-DX1', 'TCGA-A2-A04X-01Z-00-DX1', 'TCGA-A2-A0CK-01Z-00-DX1', 'TCGA-A2-A0CM-01Z-00-DX1', 'TCGA-A2-A0CP-01Z-00-DX1', 'TCGA-A2-A0CQ-01Z-00-DX1', 'TCGA-A2-A0CR-01Z-00-DX1', 'TCGA-A2-A0CT-01Z-00-DX1', 'TCGA-A2-A0CU-01Z-00-DX1', 'TCGA-A2-A0CX-01Z-00-DX1', 'TCGA-A2-A0CY-01Z-00-DX1', 'TCGA-A2-A0CZ-01Z-00-DX1', 'TCGA-A2-A0D0-01Z-00-DX1', 'TCGA-A2-A0D4-01Z-00-DX1', 'TCGA-A2-A0EN-01Z-00-DX1', 'TCGA-A2-A0EO-01Z-00-DX1', 'TCGA-A2-A0EQ-01Z-00-DX1', 'TCGA-A2-A0ER-01Z-00-DX1', 'TCGA-A2-A0ET-01Z-00-DX1', 'TCGA-A2-A0EU-01Z-00-DX1', 'TCGA-A2-A0EV-01Z-00-DX1', 'TCGA-A2-A0EW-01Z-00-DX1', 'TCGA-A2-A0EY-01Z-00-DX1', 'TCGA-A2-A0ST-01Z-00-DX1', 'TCGA-A2-A0SU-01Z-00-DX1', 'TCGA-A2-A0SV-01Z-00-DX1', 'TCGA-A2-A0SW-01Z-00-DX1', 'TCGA-A2-A0SY-01Z-00-DX1', 'TCGA-A2-A0T0-01Z-00-DX1', 'TCGA-A2-A0T1-01Z-00-DX1', 'TCGA-A2-A0T2-01Z-00-DX1', 'TCGA-A2-A0T5-01Z-00-DX1', 'TCGA-A2-A0T6-01Z-00-DX1', 'TCGA-A2-A0T7-01Z-00-DX1', 'TCGA-A2-A0YC-01Z-00-DX1', 'TCGA-A2-A0YD-01Z-00-DX1', 'TCGA-A2-A0YE-01Z-00-DX1', 'TCGA-A2-A0YF-01Z-00-DX1', 'TCGA-A2-A0YM-01Z-00-DX1', 'TCGA-A2-A0YT-01Z-00-DX1', 'TCGA-A2-A1FV-01Z-00-DX1', 'TCGA-A2-A1FW-01Z-00-DX1', 'TCGA-A2-A1FX-01Z-00-DX1', 'TCGA-A2-A1FZ-01Z-00-DX1', 'TCGA-A2-A1G0-01Z-00-DX1', 'TCGA-A2-A1G1-01Z-00-DX1', 'TCGA-A2-A1G4-01Z-00-DX1', 'TCGA-A2-A25A-01Z-00-DX1', 'TCGA-A2-A25B-01Z-00-DX1', 'TCGA-A2-A25D-01Z-00-DX1', 'TCGA-A2-A25E-01Z-00-DX1', 'TCGA-A2-A25F-01Z-00-DX1', 'TCGA-A2-A3XT-01Z-00-DX1', 'TCGA-A2-A3XU-01Z-00-DX1', 'TCGA-A2-A3XV-01Z-00-DX1', 'TCGA-A2-A3XX-01Z-00-DX1', 'TCGA-A2-A3XY-01Z-00-DX1', 'TCGA-A2-A3XZ-01Z-00-DX1', 'TCGA-A2-A3Y0-01Z-00-DX1', 'TCGA-A2-A4RX-01Z-00-DX1', 'TCGA-A2-A4S3-01Z-00-DX1', 'TCGA-A7-A26G-01Z-00-DX1', 'TCGA-A7-A2KD-01Z-00-DX1', 'TCGA-A7-A426-01Z-00-DX1', 'TCGA-A7-A4SD-01Z-00-DX1', 'TCGA-A8-A06T-01Z-00-DX1', 'TCGA-A8-A06Z-01Z-00-DX1', 'TCGA-A8-A09E-01Z-00-DX1', 'TCGA-A8-A0A4-01Z-00-DX1', 'TCGA-A8-A0A7-01Z-00-DX1', 'TCGA-AC-A23C-01Z-00-DX1', 'TCGA-AC-A23E-01Z-00-DX1', 'TCGA-AC-A2B8-01Z-00-DX1', 'TCGA-AC-A2BK-01Z-00-DX1', 'TCGA-AC-A2BM-01Z-00-DX1', 'TCGA-AC-A2FG-01Z-00-DX1', 'TCGA-AC-A2FK-01Z-00-DX1', 'TCGA-AC-A2FO-01Z-00-DX1', 'TCGA-AC-A2QJ-01Z-00-DX1', 'TCGA-AC-A3HN-01Z-00-DX1', 'TCGA-AC-A3QP-01Z-00-DX1', 'TCGA-AC-A3TM-01Z-00-DX1', 'TCGA-AC-A3YJ-01Z-00-DX1', 'TCGA-AC-A5XU-01Z-00-DX1', 'TCGA-AC-A62X-01Z-00-DX1', 'TCGA-AC-A6IW-01Z-00-DX1', 'TCGA-AC-A6NO-01Z-00-DX1', 'TCGA-AC-A7VB-01Z-00-DX1', 'TCGA-AC-A7VC-01Z-00-DX1', 'TCGA-AC-A8OQ-01Z-00-DX1', 'TCGA-AN-A0AJ-01Z-00-DX1', 'TCGA-AN-A0AK-01Z-00-DX1', 'TCGA-AN-A0AL-01Z-00-DX1', 'TCGA-AN-A0AM-01Z-00-DX1', 'TCGA-AN-A0AR-01Z-00-DX1', 'TCGA-AN-A0AS-01Z-00-DX1', 'TCGA-AN-A0AT-01Z-00-DX1', 'TCGA-AN-A0FF-01Z-00-DX1', 'TCGA-AN-A0FJ-01Z-00-DX1', 'TCGA-AN-A0FK-01Z-00-DX1', 'TCGA-AN-A0FL-01Z-00-DX1', 'TCGA-AN-A0FN-01Z-00-DX1', 'TCGA-AN-A0FS-01Z-00-DX1', 'TCGA-AN-A0FT-01Z-00-DX1', 'TCGA-AN-A0FV-01Z-00-DX1', 'TCGA-AN-A0FW-01Z-00-DX1', 'TCGA-AN-A0FX-01Z-00-DX1', 'TCGA-AN-A0FY-01Z-00-DX1', 'TCGA-AN-A0FZ-01Z-00-DX1', 'TCGA-AN-A0G0-01Z-00-DX1', 'TCGA-AN-A0XL-01Z-00-DX1', 'TCGA-AN-A0XN-01Z-00-DX1', 'TCGA-AN-A0XO-01Z-00-DX1', 'TCGA-AN-A0XP-01Z-00-DX1', 'TCGA-AN-A0XS-01Z-00-DX1', 'TCGA-AN-A0XT-01Z-00-DX1', 'TCGA-AN-A0XU-01Z-00-DX1', 'TCGA-AO-A03L-01Z-00-DX1', 'TCGA-AO-A03M-01Z-00-DX1', 'TCGA-AO-A03N-01Z-00-DX1', 'TCGA-AO-A03O-01Z-00-DX1', 'TCGA-AO-A03P-01Z-00-DX1', 'TCGA-AO-A03R-01Z-00-DX1', 'TCGA-AO-A03T-01Z-00-DX1', 'TCGA-AO-A03U-01Z-00-DX1', 'TCGA-AO-A03V-01Z-00-DX1', 'TCGA-AO-A0J2-01Z-00-DX1', 'TCGA-AO-A0J3-01Z-00-DX1', 'TCGA-AO-A0J4-01Z-00-DX1', 'TCGA-AO-A0J6-01Z-00-DX1', 'TCGA-AO-A0J7-01Z-00-DX1', 'TCGA-AO-A0J8-01Z-00-DX1', 'TCGA-AO-A0J9-01Z-00-DX1', 'TCGA-AO-A0JA-01Z-00-DX1', 'TCGA-AO-A0JB-01Z-00-DX1', 'TCGA-AO-A0JC-01Z-00-DX1', 'TCGA-AO-A0JD-01Z-00-DX1', 'TCGA-AO-A0JE-01Z-00-DX1', 'TCGA-AO-A0JF-01Z-00-DX1', 'TCGA-AO-A0JI-01Z-00-DX1', 'TCGA-AO-A0JJ-01Z-00-DX1', 'TCGA-AO-A0JL-01Z-00-DX1', 'TCGA-AO-A0JM-01Z-00-DX1', 'TCGA-AO-A124-01Z-00-DX1', 'TCGA-AO-A125-01Z-00-DX1', 'TCGA-AO-A128-01Z-00-DX1', 'TCGA-AO-A129-01Z-00-DX1', 'TCGA-AO-A12B-01Z-00-DX1', 'TCGA-AO-A12C-01Z-00-DX1', 'TCGA-AO-A12D-01Z-00-DX1', 'TCGA-AO-A12E-01Z-00-DX1', 'TCGA-AO-A12F-01Z-00-DX1', 'TCGA-AO-A12G-01Z-00-DX1', 'TCGA-AO-A12H-01Z-00-DX1', 'TCGA-AO-A1KO-01Z-00-DX1', 'TCGA-AO-A1KP-01Z-00-DX1', 'TCGA-AO-A1KQ-01Z-00-DX1', 'TCGA-AO-A1KR-01Z-00-DX1', 'TCGA-AO-A1KS-01Z-00-DX1', 'TCGA-AO-A1KT-01Z-00-DX1', 'TCGA-AQ-A04J-01Z-00-DX1', 'TCGA-AQ-A0Y5-01Z-00-DX1', 'TCGA-AQ-A54O-01Z-00-DX1', 'TCGA-AQ-A7U7-01Z-00-DX1', 'TCGA-AR-A0TP-01Z-00-DX1', 'TCGA-AR-A0TQ-01Z-00-DX1', 'TCGA-AR-A0TR-01Z-00-DX1', 'TCGA-AR-A0TS-01Z-00-DX1', 'TCGA-AR-A0TT-01Z-00-DX1', 'TCGA-AR-A0TU-01Z-00-DX1', 'TCGA-AR-A0TV-01Z-00-DX1', 'TCGA-AR-A0TW-01Z-00-DX1', 'TCGA-AR-A0TX-01Z-00-DX1', 'TCGA-AR-A0TY-01Z-00-DX1', 'TCGA-AR-A0TZ-01Z-00-DX1', 'TCGA-AR-A0U0-01Z-00-DX1', 'TCGA-AR-A0U2-01Z-00-DX1', 'TCGA-AR-A0U3-01Z-00-DX1', 'TCGA-AR-A0U4-01Z-00-DX1', 'TCGA-AR-A1AH-01Z-00-DX1', 'TCGA-AR-A1AI-01Z-00-DX1', 'TCGA-AR-A1AJ-01Z-00-DX1', 'TCGA-AR-A1AK-01Z-00-DX1', 'TCGA-AR-A1AL-01Z-00-DX1', 'TCGA-AR-A1AO-01Z-00-DX1', 'TCGA-AR-A1AP-01Z-00-DX1', 'TCGA-AR-A1AQ-01Z-00-DX1', 'TCGA-AR-A1AR-01Z-00-DX1', 'TCGA-AR-A1AS-01Z-00-DX1', 'TCGA-AR-A1AT-01Z-00-DX1', 'TCGA-AR-A1AU-01Z-00-DX1', 'TCGA-AR-A1AV-01Z-00-DX1', 'TCGA-AR-A1AW-01Z-00-DX1', 'TCGA-AR-A1AX-01Z-00-DX1', 'TCGA-AR-A1AY-01Z-00-DX1', 'TCGA-AR-A24H-01Z-00-DX1', 'TCGA-AR-A24K-01Z-00-DX1', 'TCGA-AR-A24L-01Z-00-DX1', 'TCGA-AR-A24M-01Z-00-DX1', 'TCGA-AR-A24N-01Z-00-DX1', 'TCGA-AR-A24O-01Z-00-DX1', 'TCGA-AR-A24P-01Z-00-DX1', 'TCGA-AR-A24Q-01Z-00-DX1', 'TCGA-AR-A24R-01Z-00-DX1', 'TCGA-AR-A24S-01Z-00-DX1', 'TCGA-AR-A24T-01Z-00-DX1', 'TCGA-AR-A24U-01Z-00-DX1', 'TCGA-AR-A24V-01Z-00-DX1', 'TCGA-AR-A24W-01Z-00-DX1', 'TCGA-AR-A24X-01Z-00-DX1', 'TCGA-AR-A250-01Z-00-DX1', 'TCGA-AR-A251-01Z-00-DX1', 'TCGA-AR-A252-01Z-00-DX1', 'TCGA-AR-A254-01Z-00-DX1', 'TCGA-AR-A256-01Z-00-DX1', 'TCGA-AR-A2LE-01Z-00-DX1', 'TCGA-AR-A2LH-01Z-00-DX1', 'TCGA-AR-A2LJ-01Z-00-DX1', 'TCGA-AR-A2LK-01Z-00-DX1', 'TCGA-AR-A2LL-01Z-00-DX1', 'TCGA-AR-A2LM-01Z-00-DX1', 'TCGA-AR-A2LO-01Z-00-DX1', 'TCGA-AR-A2LQ-01Z-00-DX1', 'TCGA-AR-A2LR-01Z-00-DX1', 'TCGA-AR-A5QM-01Z-00-DX1', 'TCGA-AR-A5QN-01Z-00-DX1', 'TCGA-AR-A5QP-01Z-00-DX1', 'TCGA-AR-A5QQ-01Z-00-DX1', 'TCGA-B6-A0I1-01Z-00-DX1', 'TCGA-B6-A0I6-01Z-00-DX1', 'TCGA-B6-A0IC-01Z-00-DX1', 'TCGA-B6-A0IE-01Z-00-DX1', 'TCGA-B6-A0IG-01Z-00-DX1', 'TCGA-B6-A0IH-01Z-00-DX1', 'TCGA-B6-A0IN-01Z-00-DX1', 'TCGA-B6-A0IO-01Z-00-DX1', 'TCGA-B6-A0IQ-01Z-00-DX1', 'TCGA-B6-A0RN-01Z-00-DX1', 'TCGA-B6-A0RP-01Z-00-DX1', 'TCGA-B6-A0RT-01Z-00-DX1', 'TCGA-B6-A0RV-01Z-00-DX1', 'TCGA-B6-A0WV-01Z-00-DX1', 'TCGA-B6-A0WY-01Z-00-DX1', 'TCGA-B6-A0X0-01Z-00-DX1', 'TCGA-B6-A0X4-01Z-00-DX1', 'TCGA-B6-A0X5-01Z-00-DX1', 'TCGA-B6-A1KC-01Z-00-DX1', 'TCGA-B6-A1KF-01Z-00-DX1', 'TCGA-B6-A1KN-01Z-00-DX1', 'TCGA-B6-A2IU-01Z-00-DX1', 'TCGA-BH-A0AW-01Z-00-DX1', 'TCGA-BH-A0B1-01Z-00-DX1', 'TCGA-BH-A0B4-01Z-00-DX1', 'TCGA-BH-A0B6-01Z-00-DX1', 'TCGA-BH-A0B9-01Z-00-DX1', 'TCGA-BH-A0BD-01Z-00-DX1', 'TCGA-BH-A0BF-01Z-00-DX1', 'TCGA-BH-A0C7-01Z-00-DX1', 'TCGA-BH-A0DI-01Z-00-DX1', 'TCGA-BH-A0E2-01Z-00-DX1', 'TCGA-BH-A0E6-01Z-00-DX1', 'TCGA-BH-A0E7-01Z-00-DX1', 'TCGA-BH-A0EA-01Z-00-DX1', 'TCGA-BH-A0EB-01Z-00-DX1', 'TCGA-BH-A0EE-01Z-00-DX1', 'TCGA-BH-A0GY-01Z-00-DX1', 'TCGA-BH-A0GZ-01Z-00-DX1', 'TCGA-BH-A0H6-01Z-00-DX1', 'TCGA-BH-A0HB-01Z-00-DX1', 'TCGA-BH-A0HF-01Z-00-DX1', 'TCGA-BH-A0HI-01Z-00-DX1', 'TCGA-BH-A0HL-01Z-00-DX1', 'TCGA-BH-A0HN-01Z-00-DX1', 'TCGA-BH-A0HO-01Z-00-DX1', 'TCGA-BH-A0HP-01Z-00-DX1', 'TCGA-BH-A0HQ-01Z-00-DX1', 'TCGA-BH-A0HU-01Z-00-DX1', 'TCGA-BH-A0HW-01Z-00-DX1', 'TCGA-BH-A0HX-01Z-00-DX1', 'TCGA-BH-A0HY-01Z-00-DX1', 'TCGA-BH-A0RX-01Z-00-DX1', 'TCGA-BH-A0W3-01Z-00-DX1', 'TCGA-BH-A0W4-01Z-00-DX1', 'TCGA-BH-A0W5-01Z-00-DX1', 'TCGA-BH-A0W7-01Z-00-DX1', 'TCGA-BH-A0WA-01Z-00-DX1', 'TCGA-BH-A18F-01Z-00-DX1', 'TCGA-BH-A18G-01Z-00-DX1', 'TCGA-BH-A18H-01Z-00-DX1', 'TCGA-BH-A18I-01Z-00-DX1', 'TCGA-BH-A18T-01Z-00-DX1', 'TCGA-BH-A1FL-01Z-00-DX1', 'TCGA-BH-A201-01Z-00-DX1', 'TCGA-BH-A202-01Z-00-DX1', 'TCGA-BH-A28O-01Z-00-DX1', 'TCGA-BH-A28Q-01Z-00-DX1', 'TCGA-BH-A2L8-01Z-00-DX1', 'TCGA-BH-A42T-01Z-00-DX1', 'TCGA-BH-A42U-01Z-00-DX1', 'TCGA-BH-A42V-01Z-00-DX1', 'TCGA-BH-A5IZ-01Z-00-DX1', 'TCGA-BH-A5J0-01Z-00-DX1', 'TCGA-C8-A12K-01Z-00-DX1', 'TCGA-C8-A12L-01Z-00-DX1', 'TCGA-C8-A12M-01Z-00-DX1', 'TCGA-C8-A12N-01Z-00-DX1', 'TCGA-C8-A12O-01Z-00-DX1', 'TCGA-C8-A12Q-01Z-00-DX1', 'TCGA-C8-A12T-01Z-00-DX1', 'TCGA-C8-A12U-01Z-00-DX1', 'TCGA-C8-A12V-01Z-00-DX1', 'TCGA-C8-A12W-01Z-00-DX1', 'TCGA-C8-A12Y-01Z-00-DX1', 'TCGA-C8-A12Z-01Z-00-DX1', 'TCGA-C8-A130-01Z-00-DX1', 'TCGA-C8-A131-01Z-00-DX1', 'TCGA-C8-A132-01Z-00-DX1', 'TCGA-C8-A133-01Z-00-DX1', 'TCGA-C8-A134-01Z-00-DX1', 'TCGA-C8-A135-01Z-00-DX1', 'TCGA-C8-A137-01Z-00-DX1', 'TCGA-C8-A138-01Z-00-DX1', 'TCGA-C8-A1HE-01Z-00-DX1', 'TCGA-C8-A1HF-01Z-00-DX1', 'TCGA-C8-A1HG-01Z-00-DX1', 'TCGA-C8-A1HI-01Z-00-DX1', 'TCGA-C8-A1HJ-01Z-00-DX1', 'TCGA-C8-A1HK-01Z-00-DX1', 'TCGA-C8-A1HL-01Z-00-DX1', 'TCGA-C8-A1HM-01Z-00-DX1', 'TCGA-C8-A1HN-01Z-00-DX1', 'TCGA-C8-A1HO-01Z-00-DX1', 'TCGA-C8-A26V-01Z-00-DX1', 'TCGA-C8-A26W-01Z-00-DX1', 'TCGA-C8-A26X-01Z-00-DX1', 'TCGA-C8-A26Y-01Z-00-DX1', 'TCGA-C8-A26Z-01Z-00-DX1', 'TCGA-C8-A273-01Z-00-DX1', 'TCGA-C8-A274-01Z-00-DX1', 'TCGA-C8-A275-01Z-00-DX1', 'TCGA-C8-A278-01Z-00-DX1', 'TCGA-C8-A27A-01Z-00-DX1', 'TCGA-C8-A27B-01Z-00-DX1', 'TCGA-C8-A3M7-01Z-00-DX1', 'TCGA-C8-A3M8-01Z-00-DX1', 'TCGA-C8-A8HP-01Z-00-DX1', 'TCGA-C8-A8HQ-01Z-00-DX1', 'TCGA-C8-A8HR-01Z-00-DX1', 'TCGA-D8-A13Z-01Z-00-DX1', 'TCGA-D8-A142-01Z-00-DX1', 'TCGA-D8-A143-01Z-00-DX1', 'TCGA-D8-A146-01Z-00-DX1', 'TCGA-D8-A147-01Z-00-DX1', 'TCGA-D8-A1JA-01Z-00-DX1', 'TCGA-D8-A1JB-01Z-00-DX1', 'TCGA-D8-A1JF-01Z-00-DX1', 'TCGA-D8-A1JG-01Z-00-DX1', 'TCGA-D8-A1JH-01Z-00-DX1', 'TCGA-D8-A1JK-01Z-00-DX1', 'TCGA-D8-A1JL-01Z-00-DX1', 'TCGA-D8-A1JM-01Z-00-DX1', 'TCGA-D8-A1JN-01Z-00-DX1', 'TCGA-D8-A1JP-01Z-00-DX1', 'TCGA-D8-A1JS-01Z-00-DX1', 'TCGA-D8-A1JU-01Z-00-DX1', 'TCGA-D8-A1X8-01Z-00-DX1', 'TCGA-D8-A1X9-01Z-00-DX1', 'TCGA-D8-A1XD-01Z-00-DX1', 'TCGA-D8-A1XG-01Z-00-DX1', 'TCGA-D8-A1XJ-01Z-00-DX1', 'TCGA-D8-A1XK-01Z-00-DX1', 'TCGA-D8-A1XM-01Z-00-DX1', 'TCGA-D8-A1XO-01Z-00-DX1', 'TCGA-D8-A1XQ-01Z-00-DX1', 'TCGA-D8-A1XT-01Z-00-DX1', 'TCGA-D8-A1XU-01Z-00-DX1', 'TCGA-D8-A27E-01Z-00-DX1', 'TCGA-D8-A27F-01Z-00-DX1', 'TCGA-D8-A27G-01Z-00-DX1', 'TCGA-D8-A27H-01Z-00-DX1', 'TCGA-D8-A27I-01Z-00-DX1', 'TCGA-D8-A27K-01Z-00-DX1', 'TCGA-D8-A27L-01Z-00-DX1', 'TCGA-D8-A27M-01Z-00-DX1', 'TCGA-D8-A4Z1-01Z-00-DX1', 'TCGA-E2-A105-01Z-00-DX1', 'TCGA-E2-A106-01Z-00-DX1', 'TCGA-E2-A107-01Z-00-DX1', 'TCGA-E2-A108-01Z-00-DX1', 'TCGA-E2-A109-01Z-00-DX1', 'TCGA-E2-A10A-01Z-00-DX1', 'TCGA-E2-A10B-01Z-00-DX1', 'TCGA-E2-A10C-01Z-00-DX1', 'TCGA-E2-A10E-01Z-00-DX1', 'TCGA-E2-A10F-01Z-00-DX1', 'TCGA-E2-A14N-01Z-00-DX1', 'TCGA-E2-A14O-01Z-00-DX1', 'TCGA-E2-A14P-01Z-00-DX1', 'TCGA-E2-A14Q-01Z-00-DX1', 'TCGA-E2-A14R-01Z-00-DX1', 'TCGA-E2-A14S-01Z-00-DX1', 'TCGA-E2-A14T-01Z-00-DX1', 'TCGA-E2-A14U-01Z-00-DX1', 'TCGA-E2-A14V-01Z-00-DX1', 'TCGA-E2-A14W-01Z-00-DX1', 'TCGA-E2-A14X-01Z-00-DX1', 'TCGA-E2-A14Y-01Z-00-DX1', 'TCGA-E2-A14Z-01Z-00-DX1', 'TCGA-E2-A150-01Z-00-DX1', 'TCGA-E2-A152-01Z-00-DX1', 'TCGA-E2-A154-01Z-00-DX1', 'TCGA-E2-A155-01Z-00-DX1', 'TCGA-E2-A156-01Z-00-DX1', 'TCGA-E2-A159-01Z-00-DX1', 'TCGA-E2-A15C-01Z-00-DX1', 'TCGA-E2-A15D-01Z-00-DX1', 'TCGA-E2-A15F-01Z-00-DX1', 'TCGA-E2-A15G-01Z-00-DX1', 'TCGA-E2-A15H-01Z-00-DX1', 'TCGA-E2-A15J-01Z-00-DX1', 'TCGA-E2-A15L-01Z-00-DX1', 'TCGA-E2-A15O-01Z-00-DX1', 'TCGA-E2-A15P-01Z-00-DX1', 'TCGA-E2-A15R-01Z-00-DX1', 'TCGA-E2-A15S-01Z-00-DX1', 'TCGA-E2-A15T-01Z-00-DX1', 'TCGA-E2-A1AZ-01Z-00-DX1', 'TCGA-E2-A1B0-01Z-00-DX1', 'TCGA-E2-A1B1-01Z-00-DX1', 'TCGA-E2-A1B4-01Z-00-DX1', 'TCGA-E2-A1B5-01Z-00-DX1', 'TCGA-E2-A1B6-01Z-00-DX1', 'TCGA-E2-A1BD-01Z-00-DX1', 'TCGA-E2-A1IE-01Z-00-DX1', 'TCGA-E2-A1IF-01Z-00-DX1', 'TCGA-E2-A1IH-01Z-00-DX1', 'TCGA-E2-A1II-01Z-00-DX1', 'TCGA-E2-A1IK-01Z-00-DX1', 'TCGA-E2-A1IO-01Z-00-DX1', 'TCGA-E2-A1IU-01Z-00-DX1', 'TCGA-E2-A1L6-01Z-00-DX1', 'TCGA-E2-A1L9-01Z-00-DX1', 'TCGA-E2-A1LA-01Z-00-DX1', 'TCGA-E2-A1LE-01Z-00-DX1', 'TCGA-E2-A1LG-01Z-00-DX1', 'TCGA-E2-A1LI-01Z-00-DX1', 'TCGA-E2-A1LK-01Z-00-DX1', 'TCGA-E2-A1LL-01Z-00-DX1', 'TCGA-E2-A2P5-01Z-00-DX1', 'TCGA-E2-A2P6-01Z-00-DX1', 'TCGA-E2-A3DX-01Z-00-DX1', 'TCGA-E2-A56Z-01Z-00-DX1', 'TCGA-E2-A570-01Z-00-DX1', 'TCGA-E2-A572-01Z-00-DX1', 'TCGA-E2-A573-01Z-00-DX1', 'TCGA-E2-A574-01Z-00-DX1', 'TCGA-E2-A576-01Z-00-DX1', 'TCGA-E2-A9RU-01Z-00-DX1', 'TCGA-E9-A229-01Z-00-DX1', 'TCGA-E9-A22B-01Z-00-DX1', 'TCGA-E9-A22D-01Z-00-DX1', 'TCGA-E9-A22G-01Z-00-DX1', 'TCGA-E9-A244-01Z-00-DX1', 'TCGA-E9-A245-01Z-00-DX1', 'TCGA-E9-A247-01Z-00-DX1', 'TCGA-E9-A248-01Z-00-DX1', 'TCGA-E9-A3HO-01Z-00-DX1', 'TCGA-E9-A3QA-01Z-00-DX1', 'TCGA-E9-A54Y-01Z-00-DX1', 'TCGA-E9-A5UP-01Z-00-DX1', 'TCGA-EW-A1IW-01Z-00-DX1', 'TCGA-EW-A1IX-01Z-00-DX1', 'TCGA-EW-A1IY-01Z-00-DX1', 'TCGA-EW-A1IZ-01Z-00-DX1', 'TCGA-EW-A1J1-01Z-00-DX1', 'TCGA-EW-A1J2-01Z-00-DX1', 'TCGA-EW-A1J3-01Z-00-DX1', 'TCGA-EW-A1J5-01Z-00-DX1', 'TCGA-EW-A1J6-01Z-00-DX1', 'TCGA-EW-A1OV-01Z-00-DX1', 'TCGA-EW-A1OW-01Z-00-DX1', 'TCGA-EW-A1OX-01Z-00-DX1', 'TCGA-EW-A1OY-01Z-00-DX1', 'TCGA-EW-A1OZ-01Z-00-DX1', 'TCGA-EW-A1P1-01Z-00-DX1', 'TCGA-EW-A1P3-01Z-00-DX1', 'TCGA-EW-A1P4-01Z-00-DX1', 'TCGA-EW-A1P5-01Z-00-DX1', 'TCGA-EW-A1P6-01Z-00-DX1', 'TCGA-EW-A1P7-01Z-00-DX1', 'TCGA-EW-A1P8-01Z-00-DX1', 'TCGA-EW-A1PA-01Z-00-DX1', 'TCGA-EW-A1PB-01Z-00-DX1', 'TCGA-EW-A1PC-01Z-00-DX1', 'TCGA-EW-A1PD-01Z-00-DX1', 'TCGA-EW-A1PE-01Z-00-DX1', 'TCGA-EW-A1PF-01Z-00-DX1', 'TCGA-EW-A1PG-01Z-00-DX1', 'TCGA-EW-A1PH-01Z-00-DX1', 'TCGA-EW-A2FR-01Z-00-DX1', 'TCGA-EW-A2FS-01Z-00-DX1', 'TCGA-EW-A2FV-01Z-00-DX1', 'TCGA-EW-A2FW-01Z-00-DX1', 'TCGA-EW-A3E8-01Z-00-DX1', 'TCGA-EW-A3U0-01Z-00-DX1', 'TCGA-EW-A424-01Z-00-DX1', 'TCGA-EW-A6S9-01Z-00-DX1', 'TCGA-EW-A6SA-01Z-00-DX1', 'TCGA-EW-A6SB-01Z-00-DX1', 'TCGA-EW-A6SC-01Z-00-DX1', 'TCGA-EW-A6SD-01Z-00-DX1', 'TCGA-GM-A2D9-01Z-00-DX1', 'TCGA-GM-A2DB-01Z-00-DX1', 'TCGA-GM-A2DC-01Z-00-DX1', 'TCGA-GM-A2DD-01Z-00-DX1', 'TCGA-GM-A2DF-01Z-00-DX1', 'TCGA-GM-A2DH-01Z-00-DX1', 'TCGA-GM-A2DI-01Z-00-DX1', 'TCGA-GM-A2DK-01Z-00-DX1', 'TCGA-GM-A2DL-01Z-00-DX1', 'TCGA-GM-A2DM-01Z-00-DX1', 'TCGA-GM-A2DN-01Z-00-DX1', 'TCGA-GM-A2DO-01Z-00-DX1', 'TCGA-GM-A3NW-01Z-00-DX1', 'TCGA-GM-A3NY-01Z-00-DX1', 'TCGA-GM-A3XG-01Z-00-DX1', 'TCGA-GM-A3XL-01Z-00-DX1', 'TCGA-GM-A3XN-01Z-00-DX1', 'TCGA-GM-A4E0-01Z-00-DX1', 'TCGA-HN-A2NL-01Z-00-DX1', 'TCGA-LD-A66U-01Z-00-DX1', 'TCGA-LD-A74U-01Z-00-DX1', 'TCGA-LD-A7W5-01Z-00-DX1', 'TCGA-LD-A7W6-01Z-00-DX1', 'TCGA-LD-A9QF-01Z-00-DX1', 'TCGA-LL-A440-01Z-00-DX1', 'TCGA-LL-A441-01Z-00-DX1', 'TCGA-LL-A442-01Z-00-DX1', 'TCGA-LL-A50Y-01Z-00-DX1', 'TCGA-LL-A5YL-01Z-00-DX1', 'TCGA-LL-A5YM-01Z-00-DX1', 'TCGA-LL-A5YN-01Z-00-DX1', 'TCGA-LL-A5YO-01Z-00-DX1', 'TCGA-LL-A5YP-01Z-00-DX1', 'TCGA-LL-A6FP-01Z-00-DX1', 'TCGA-LL-A6FQ-01Z-00-DX1', 'TCGA-LL-A6FR-01Z-00-DX1', 'TCGA-LL-A73Y-01Z-00-DX1', 'TCGA-LL-A73Z-01Z-00-DX1', 'TCGA-LL-A740-01Z-00-DX1', 'TCGA-LL-A7SZ-01Z-00-DX1', 'TCGA-LL-A7T0-01Z-00-DX1', 'TCGA-LL-A8F5-01Z-00-DX1', 'TCGA-LL-A9Q3-01Z-00-DX1', 'TCGA-LQ-A4E4-01Z-00-DX1', 'TCGA-OL-A5D7-01Z-00-DX1', 'TCGA-OL-A5D8-01Z-00-DX1', 'TCGA-OL-A5DA-01Z-00-DX1', 'TCGA-OL-A6VQ-01Z-00-DX1', 'TCGA-OL-A97C-01Z-00-DX1', 'TCGA-PE-A5DC-01Z-00-DX1', 'TCGA-PE-A5DD-01Z-00-DX1', 'TCGA-PE-A5DE-01Z-00-DX1', 'TCGA-S3-A6ZF-01Z-00-DX1', 'TCGA-S3-A6ZG-01Z-00-DX1', 'TCGA-S3-AA0Z-01Z-00-DX1', 'TCGA-S3-AA10-01Z-00-DX1', 'TCGA-S3-AA11-01Z-00-DX1', 'TCGA-S3-AA14-01Z-00-DX1', 'TCGA-S3-AA17-01Z-00-DX1', 'TCGA-UL-AAZ6-01Z-00-DX1', 'TCGA-UU-A93S-01Z-00-DX1', 'TCGA-W8-A86G-01Z-00-DX2', 'TCGA-XX-A899-01Z-00-DX1', 'TCGA-XX-A89A-01Z-00-DX1'])

In [10]:
pred_id_mena_dict['TCGA-3C-AALK-01Z-00-DX1'].shape

(39,)

In [11]:
import numpy as np

pred_df_list = []
for case in pred_id_mena_dict.keys():
    pred_df = pd.DataFrame(data=np.expand_dims(pred_id_mena_dict[case], axis=0), columns=cell_names, index=[case])
    pred_df_list.append(pred_df)

In [12]:
pred_all_case_df = pd.concat(pred_df_list, join='inner')
pred_all_case_df.head(2)

,CD4-positive helper T cell,"CD4-positive, alpha-beta T cell","CD8-positive, alpha-beta memory T cell",IgA plasma cell,IgG plasma cell,T cell,"activated CD4-positive, alpha-beta T cell","activated CD8-positive, alpha-beta T cell",alternatively activated macrophage,basal cell,...,naive B cell,natural killer cell,neutrophil,non-classical monocyte,pericyte,plasmacytoid dendritic cell,regulatory T cell,unswitched memory B cell,vascular associated smooth muscle cell,vein endothelial cell
TCGA-3C-AALK-01Z-00-DX1,0.160704,0.221731,0.105877,1.572897,1.550151,0.039653,0.158888,0.780631,0.042309,0.400047,...,0.13908,0.243357,0.274147,0.143055,0.099567,0.431812,0.253349,0.102376,0.796682,0.079286
TCGA-4H-AAAK-01Z-00-DX1,0.306479,0.564471,0.156112,0.888829,0.700434,-0.041915,0.277069,2.113774,0.079509,0.217030,...,0.26064,0.287138,0.191035,0.218524,0.158000,0.309171,0.649358,0.164299,0.600419,0.160729

In [13]:
label_idx_set = set(brca_cell_label_df.index)
pred_idx_set = set(pred_all_case_df.index)
selected_idx_set = label_idx_set.intersection(pred_idx_set)
len(selected_idx_set)

585

In [14]:
selected_idx_list = list(selected_idx_set)

In [15]:
seleted_label_df = brca_cell_label_df.loc[selected_idx_list, :]
seleted_label_df.head(2)

,q05cell_abundance_w_sf_CD4-positive helper T cell,"q05cell_abundance_w_sf_CD4-positive, alpha-beta T cell","q05cell_abundance_w_sf_CD8-positive, alpha-beta memory T cell",q05cell_abundance_w_sf_IgA plasma cell,q05cell_abundance_w_sf_IgG plasma cell,q05cell_abundance_w_sf_T cell,"q05cell_abundance_w_sf_activated CD4-positive, alpha-beta T cell","q05cell_abundance_w_sf_activated CD8-positive, alpha-beta T cell",q05cell_abundance_w_sf_alternatively activated macrophage,q05cell_abundance_w_sf_basal cell,...,q05cell_abundance_w_sf_naive B cell,q05cell_abundance_w_sf_natural killer cell,q05cell_abundance_w_sf_neutrophil,q05cell_abundance_w_sf_non-classical monocyte,q05cell_abundance_w_sf_pericyte,q05cell_abundance_w_sf_plasmacytoid dendritic cell,q05cell_abundance_w_sf_regulatory T cell,q05cell_abundance_w_sf_unswitched memory B cell,q05cell_abundance_w_sf_vascular associated smooth muscle cell,q05cell_abundance_w_sf_vein endothelial cell
TCGA-B6-A0I6-01Z-00-DX1,0.000239,0.000131,0.000087,0.006001,0.041495,0.102806,0.000028,0.000039,0.022900,2.306617,...,0.000195,0.000011,0.002859,0.000094,0.081313,0.000027,0.000107,0.001025,0.434610,0.000122
TCGA-AR-A5QN-01Z-00-DX1,0.140585,0.005811,0.012704,0.010144,0.004763,0.002964,0.002598,0.004900,0.214371,0.360983,...,0.010447,0.010290,0.006641,0.000080,0.322384,0.011561,0.000298,0.000704,0.396694,0.247692

In [16]:
seleted_pred_df = pred_all_case_df.loc[selected_idx_list, :]
seleted_pred_df.head(2)

,CD4-positive helper T cell,"CD4-positive, alpha-beta T cell","CD8-positive, alpha-beta memory T cell",IgA plasma cell,IgG plasma cell,T cell,"activated CD4-positive, alpha-beta T cell","activated CD8-positive, alpha-beta T cell",alternatively activated macrophage,basal cell,...,naive B cell,natural killer cell,neutrophil,non-classical monocyte,pericyte,plasmacytoid dendritic cell,regulatory T cell,unswitched memory B cell,vascular associated smooth muscle cell,vein endothelial cell
TCGA-B6-A0I6-01Z-00-DX1,0.477686,0.929766,0.233456,0.970570,1.595926,0.005502,0.440688,3.44701,0.080086,0.232039,...,0.409089,0.518483,0.312588,0.334057,0.193691,0.522132,1.061253,0.268876,0.451059,0.229690
TCGA-AR-A5QN-01Z-00-DX1,0.120034,0.186837,0.079740,2.534133,3.685647,-0.008353,0.127680,1.01922,0.027689,0.130074,...,0.097090,0.403516,0.449560,0.192438,0.089847,0.746636,0.243145,0.065414,0.629399,0.113727

In [17]:
normalized_seleted_pred_df = seleted_pred_df.apply(lambda row: row / row.sum(), axis=1)
normalized_seleted_label_df = seleted_label_df.apply(lambda row: row / row.sum(), axis=1)

In [28]:
from scipy.stats import pearsonr

test_cell_pearson_list = list()
test_cell_abundance_pos_pearson_average = 0.0
test_cell_abundance_all_pearson_average = 0.0
test_cell_abundance_pos_pearson_count = 0
for i in range(39):
    r, p = pearsonr(normalized_seleted_pred_df.iloc[:, i], normalized_seleted_label_df.iloc[:, i])
    if r > 0.0:
        test_cell_abundance_pos_pearson_count = test_cell_abundance_pos_pearson_count + 1
        test_cell_abundance_pos_pearson_average = test_cell_abundance_pos_pearson_average + r
    if np.isnan(r):
        r = 0.0
    test_cell_abundance_all_pearson_average = test_cell_abundance_all_pearson_average + r
    test_cell_pearson_list.append(r)
if test_cell_abundance_pos_pearson_count >= 1:
    test_cell_abundance_pos_pearson_average /= test_cell_abundance_pos_pearson_count
else:
    test_cell_abundance_pos_pearson_average = 0.0
test_cell_abundance_all_pearson_average = test_cell_abundance_all_pearson_average / 39

In [29]:
test_cell_abundance_pos_pearson_count

26

In [30]:
test_cell_abundance_pos_pearson_average

0.13489525980934008

In [31]:
test_cell_abundance_all_pearson_average

0.06331109350616095

In [32]:
test_cell_pearson_dict = dict()
for i in range(39):
    test_cell_pearson_dict[cell_names[i]] = test_cell_pearson_list[i]
test_cell_pearson_dict

{'CD4-positive helper T cell': -0.1119309587304602,
 'CD4-positive, alpha-beta T cell': 0.0530471323843932,
 'CD8-positive, alpha-beta memory T cell': 0.04937037831622928,
 'IgA plasma cell': -0.011784547102464907,
 'IgG plasma cell': -0.06500919018861377,
 'T cell': -0.03219448325806972,
 'activated CD4-positive, alpha-beta T cell': 0.07470682508400259,
 'activated CD8-positive, alpha-beta T cell': 0.16412952682574675,
 'alternatively activated macrophage': -0.15978022742651365,
 'basal cell': 0.12044029161702147,
 'capillary endothelial cell': 0.05117196219013015,
 'class switched memory B cell': 0.05365789768666823,
 'classical monocyte': -0.016321766831180556,
 'conventional dendritic cell': -0.027207944075229883,
 'effector memory CD4-positive, alpha-beta T cell': 0.01071102062169887,
 'effector memory CD8-positive, alpha-beta T cell': 0.09303558957334802,
 'endothelial cell of artery': 0.2123365486995114,
 'endothelial cell of lymphatic vessel': 0.32468682777286684,
 'fibroblast': 0.399669060907584,
 'gamma-delta T cell': -0.03494568912974285,
 'inflammatory macrophage': -0.11218210843073038,
 'luminal epithelial cell of mammary gland': 0.1961070405959291,
 'lymphocyte': 0.05030674797587261,
 'macrophage': 0.07573361190744847,
 'mammary gland epithelial cell': -0.25806830468457004,
 'mast cell': -0.06306553661069643,
 'mature NK T cell': 0.14935285238449234,
 'myeloid cell': 0.04216621874200223,
 'myeloid dendritic cell': 0.23187061747486729,
 'naive B cell': 0.19605067387525635,
 'natural killer cell': 0.11420859806392628,
 'neutrophil': 0.027549354500980134,
 'non-classical monocyte': 0.03547887641951824,
 'pericyte': 0.028562361165288205,
 'plasmacytoid dendritic cell': -0.057054707956502984,
 'regulatory T cell': 0.17579453023796957,
 'unswitched memory B cell': 0.21929811896203555,
 'vascular associated smooth muscle cell': 0.3578340910580551,
 'vein endothelial cell': -0.08859864387778901}

Maybe 77 samples are not enough